#include "fractal/local_workspace_service.h"
#include <string.h>
#include <unistd.h>
static fractal_workspace_id id_make(uint64_t high,uint64_t low){fractal_workspace_id id={high,low};return id;}
static uint64_t hash_bytes(uint64_t h,const void*p,size_t n){const unsigned char*b=(const unsigned char*)p;size_t i;for(i=0;i<n;i++){h^=b[i];h*=UINT64_C(1099511628211);}return h;}
static uint64_t checksum_checkpoint(const fractal_local_checkpoint*c){uint64_t h=UINT64_C(1469598103934665603);h=hash_bytes(h,&c->magic,sizeof(c->magic));h=hash_bytes(h,&c->version,sizeof(c->version));h=hash_bytes(h,&c->workspace,sizeof(c->workspace));h=hash_bytes(h,&c->lifetime,sizeof(c->lifetime));h=hash_bytes(h,&c->replay,sizeof(c->replay));return h;}
const char*fractal_workspace_lifetime_state_name(fractal_workspace_lifetime_state s){static const char*n[]={"UNINITIALIZED","CREATED","OPEN","ACTIVE","IDLE","CHECKPOINTING","RESTORING","CLOSING","CLOSED","FAILED"};return s<=FRACTAL_WS_FAILED?n[s]:"FAILED";}
const char*fractal_service_lifecycle_name(fractal_service_lifecycle s){static const char*n[]={"STOPPED","STARTING","INITIALIZING","READY","DRAINING","STOPPING","FAILED"};return s<=FRACTAL_SERVICE_FAILED?n[s]:"FAILED";}
const char*fractal_local_message_class_name(fractal_local_message_class c){static const char*n[]={"INVALID","COMPATIBILITY_HELLO","COMPATIBILITY_RESULT","LOCAL_SESSION_OPEN","LOCAL_SESSION_RESULT","WORKSPACE_OPEN","WORKSPACE_SNAPSHOT_REQUEST","WORKSPACE_SNAPSHOT","CLIENT_INTENT","WORKSPACE_TRANSITION","REACQUIRE_REQUEST","REACQUIRE_RESPONSE","SERVICE_STATUS_REQUEST","SERVICE_STATUS","SESSION_CLOSE","PROTOCOL_ERROR"};return c<=FRACTAL_MSG_PROTOCOL_ERROR?n[c]:"PROTOCOL_ERROR";}
int fractal_workspace_lifetime_transition(fractal_workspace_lifetime_record*r,fractal_workspace_lifetime_state n,uint64_t e){bool ok=false;if(!r)return-1;switch(r->state){case FRACTAL_WS_UNINITIALIZED:ok=n==FRACTAL_WS_CREATED||n==FRACTAL_WS_RESTORING;break;case FRACTAL_WS_CREATED:ok=n==FRACTAL_WS_OPEN;break;case FRACTAL_WS_OPEN:ok=n==FRACTAL_WS_ACTIVE||n==FRACTAL_WS_CHECKPOINTING||n==FRACTAL_WS_CLOSING||n==FRACTAL_WS_IDLE;break;case FRACTAL_WS_ACTIVE:ok=n==FRACTAL_WS_IDLE||n==FRACTAL_WS_CHECKPOINTING||n==FRACTAL_WS_CLOSING;break;case FRACTAL_WS_IDLE:ok=n==FRACTAL_WS_ACTIVE||n==FRACTAL_WS_CHECKPOINTING||n==FRACTAL_WS_CLOSING;break;case FRACTAL_WS_CHECKPOINTING:ok=n==FRACTAL_WS_OPEN||n==FRACTAL_WS_ACTIVE||n==FRACTAL_WS_IDLE;break;case FRACTAL_WS_RESTORING:ok=n==FRACTAL_WS_OPEN||n==FRACTAL_WS_IDLE;break;case FRACTAL_WS_CLOSING:ok=n==FRACTAL_WS_CLOSED;break;default:ok=false;break;}if(!ok){r->state=FRACTAL_WS_FAILED;r->bounded_error=1u;return-1;}r->state=n;r->lifecycle_epoch++;r->service_restart_epoch=e;return 0;}
void fractal_local_service_init(fractal_local_service*s,uint64_t restart_epoch){if(!s)return;memset(s,0,sizeof(*s));s->lifecycle=FRACTAL_SERVICE_INITIALIZING;s->service_id=id_make(FRACTAL_LOCAL_SERVICE_ID_HIGH,FRACTAL_LOCAL_SERVICE_ID_LOW);s->restart_epoch=restart_epoch;s->local_participant=id_make(UINT64_C(0x4c4f43414c555345),UINT64_C(0x5200000000000001));s->lifetime.state=FRACTAL_WS_UNINITIALIZED;s->lifetime.service_restart_epoch=restart_epoch;fractal_replay_cache_init(&s->replay,1u);}
fractal_local_peer_result fractal_local_operator_admit_current_user(void){fractal_local_peer_result r={true,0u,0u};r.normalized_peer_identity=UINT64_C(0x4c4f43414c000000)^((uint64_t)getuid()+1u);return r;}
int fractal_local_service_open(fractal_local_service*s){if(!s)return-1;s->lifecycle=FRACTAL_SERVICE_READY;if(s->lifetime.state==FRACTAL_WS_UNINITIALIZED){fractal_workspace_lifetime_transition(&s->lifetime,FRACTAL_WS_CREATED,s->restart_epoch);if(fractal_workspace_init(&s->workspace,1u,s->local_participant,"Reference Workspace")!=0)return-1;s->lifetime.workspace_id=s->workspace.id;s->lifetime.state_revision=s->workspace.revision;s->lifetime.generation=s->workspace.generation.number;fractal_workspace_lifetime_transition(&s->lifetime,FRACTAL_WS_OPEN,s->restart_epoch);}return 0;}
int fractal_local_service_open_session(fractal_local_service*s,fractal_local_peer_result p,fractal_participant_id*out){if(!s||!p.accepted||s->active_sessions>=FRACTAL_LOCAL_SERVICE_MAX_SESSIONS)return-1;s->active_sessions++;s->lifetime.open_participant_count=s->active_sessions;if(out)*out=s->local_participant;return 0;}
static uint64_t payload_id(const fractal_client_intent*i){return hash_bytes(UINT64_C(1469598103934665603),i,sizeof(*i));}
fractal_local_transition_result fractal_local_service_apply_intent(fractal_local_service*s,const fractal_client_intent*i){fractal_local_transition_result r;fractal_workspace_transition t;memset(&r,0,sizeof(r));if(!s||!i){r.replay_kind=FRACTAL_REPLAY_CAPACITY_EXHAUSTED;return r;}for(uint32_t n=0u;n<s->replay.count;n++){fractal_replay_record*e=&s->replay.records[n];if(e->occupied&&fractal_workspace_id_equal(e->participant_id,i->participant_id)&&e->command_sequence==i->command_sequence){if(fractal_workspace_id_equal(e->intent_identity,i->identity)&&e->payload_identity==payload_id(i)){r.replay_kind=FRACTAL_REPLAY_IDENTICAL_RESULT;r.transition=e->transition;fractal_workspace_snapshot_build(&s->workspace,i->participant_id,&r.snapshot);return r;}r.replay_kind=FRACTAL_COMMAND_SEQUENCE_CONFLICT;r.transition.accepted=false;r.transition.rejection=FRACTAL_REJECT_DUPLICATE_COMMAND;return r;}}t=fractal_workspace_reduce(&s->workspace,i);r.replay_kind=FRACTAL_REPLAY_NEW_ACCEPTED;if(t.accepted){fractal_replay_result rr=fractal_replay_cache_apply(&s->replay,i,payload_id(i),t);r.replay_kind=rr.kind;r.transition=rr.transition;s->lifetime.last_transition_identity=i->identity;}else r.transition=t;s->lifetime.state_revision=s->workspace.revision;s->lifetime.generation=s->workspace.generation.number;s->lifetime.active_controller=s->workspace.lease.status==FRACTAL_LEASE_ACTIVE;fractal_workspace_snapshot_build(&s->workspace,i->participant_id,&r.snapshot);return r;}
fractal_reacquire_response fractal_local_service_reacquire(fractal_local_service*s,const fractal_reacquire_request*q){fractal_reacquire_response r;memset(&r,0,sizeof(r));r.contract_version=FRACTAL_REACQUIRE_CONTRACT_VERSION;if(!s||!q||!fractal_workspace_id_equal(q->service_id,s->service_id)){r.kind=FRACTAL_REACQUIRE_SERVICE_IDENTITY_CHANGED;return r;}if(!fractal_workspace_id_equal(q->workspace_id,s->workspace.id)){r.kind=FRACTAL_REACQUIRE_WORKSPACE_NOT_FOUND;return r;}r.current_workspace_revision=s->workspace.revision;r.current_generation=s->workspace.generation.number;r.service_restart_epoch=s->restart_epoch;r.replay_cache.first_retained_sequence=s->replay.first_retained_sequence;r.replay_cache.retained_count=s->replay.count;r.latest_accepted_client_command_sequence=q->last_accepted_command_sequence;r.kind=(q->last_accepted_workspace_revision==s->workspace.revision&&q->last_known_generation==s->workspace.generation.number)?FRACTAL_REACQUIRE_ALREADY_SYNCHRONIZED:FRACTAL_REACQUIRE_FULL_SNAPSHOT;fractal_workspace_snapshot_build(&s->workspace,q->participant_id,&r.snapshot);r.capability_set=r.snapshot.actor_capabilities;r.controller_lease=r.snapshot.lease;r.preview_identity=r.snapshot.preview_reference;r.deterministic_reacquisition_identity=hash_bytes(UINT64_C(1469598103934665603),&r.current_workspace_revision,sizeof(r.current_workspace_revision));return r;}
int fractal_local_service_snapshot(fractal_local_service*s,fractal_participant_id a,fractal_workspace_snapshot*out){return s?fractal_workspace_snapshot_build(&s->workspace,a,out):-1;}
fractal_local_service_status fractal_local_service_get_status(fractal_local_service*s){fractal_local_service_status z;memset(&z,0,sizeof(z));if(!s)return z;z.lifecycle=s->lifecycle;z.service_id=s->service_id;z.restart_epoch=s->restart_epoch;z.compatibility_selection=1u;z.workspace_count=1u;z.workspace_lifecycle=s->lifetime.state;z.revision=s->workspace.revision;z.generation=s->workspace.generation.number;z.active_sessions=s->active_sessions;z.controller_lease_active=s->workspace.lease.status==FRACTAL_LEASE_ACTIVE;z.last_checkpoint_result=s->lifetime.restoration_result;z.runtime_available=true;return z;}
int fractal_local_checkpoint_create(fractal_local_service*s,fractal_local_checkpoint*out){fractal_workspace_lifetime_state prev;if(!s||!out)return-1;prev=s->lifetime.state;if(fractal_workspace_lifetime_transition(&s->lifetime,FRACTAL_WS_CHECKPOINTING,s->restart_epoch)!=0)return-1;memset(out,0,sizeof(*out));out->magic=FRACTAL_LOCAL_CHECKPOINT_MAGIC;out->version=1u;out->size=(uint32_t)sizeof(*out);out->workspace=s->workspace;s->lifetime.checkpoint_revision=s->workspace.revision;out->lifetime=s->lifetime;out->replay=s->replay;out->checksum=checksum_checkpoint(out);s->lifetime.restoration_result=0u;s->lifetime.checkpoint_revision=s->workspace.revision;s->lifetime.state=prev;s->lifetime.lifecycle_epoch++;return 0;}
int fractal_local_checkpoint_restore(fractal_local_service*s,const fractal_local_checkpoint*c,uint64_t e){if(!s||!c)return-1;fractal_local_service_init(s,e);s->lifecycle=FRACTAL_SERVICE_STARTING;fractal_workspace_lifetime_transition(&s->lifetime,FRACTAL_WS_RESTORING,e);if(c->magic!=FRACTAL_LOCAL_CHECKPOINT_MAGIC||c->version!=1u||c->size!=sizeof(*c)||checksum_checkpoint(c)!=c->checksum){s->lifetime.state=FRACTAL_WS_FAILED;s->lifetime.restoration_result=2u;return-1;}s->workspace=c->workspace;s->replay=c->replay;s->lifetime=c->lifetime;s->lifetime.service_restart_epoch=e;s->restart_epoch=e;s->lifecycle=FRACTAL_SERVICE_READY;return fractal_workspace_lifetime_transition(&s->lifetime,FRACTAL_WS_IDLE,e);}
int fractal_local_frame_encode(const uint8_t*p,uint32_t n,uint8_t*out,size_t cap,size_t*w){if(!p||!out||!w||n>FRACTAL_LOCAL_SERVICE_FRAME_LIMIT||cap<(size_t)n+4u)return-1;out[0]=(uint8_t)(n>>24);out[1]=(uint8_t)(n>>16);out[2]=(uint8_t)(n>>8);out[3]=(uint8_t)n;memcpy(out+4,p,n);*w=(size_t)n+4u;return 0;}
int fractal_local_frame_decode(const uint8_t*in,size_t sz,uint8_t*out,size_t cap,size_t*ps,size_t*cons){uint32_t n;if(!in||!out||!ps||!cons||sz<4u)return-1;n=((uint32_t)in[0]<<24)|((uint32_t)in[1]<<16)|((uint32_t)in[2]<<8)|in[3];if(n>FRACTAL_LOCAL_SERVICE_FRAME_LIMIT||n>cap)return-2;if(sz<(size_t)n+4u)return-1;memcpy(out,in+4,n);*ps=n;*cons=(size_t)n+4u;return 0;}
uint64_t fractal_local_semantic_digest(const fractal_local_service*s){uint64_t h=UINT64_C(1469598103934665603);if(!s)return 0u;h=hash_bytes(h,&s->workspace.id,sizeof(s->workspace.id));h=hash_bytes(h,&s->workspace.revision,sizeof(s->workspace.revision));h=hash_bytes(h,&s->workspace.generation.number,sizeof(s->workspace.generation.number));h=hash_bytes(h,&s->workspace.generation.identity,sizeof(s->workspace.generation.identity));h=hash_bytes(h,&s->workspace.lease.status,sizeof(s->workspace.lease.status));return h;}
