#include "fractal/validation/transport_validation.h"
#include <string.h>
static fractal_workspace_id vid(uint64_t v){fractal_workspace_id r={UINT64_C(0x7600000000000000)|v,UINT64_C(0x5100000000000000)|(v*17u)};return r;}
static const fractal_validation_scenario scenarios[]={
{.contract_version=1,.scenario_id="validation.semantic.clean-connection-and-synchronization.v1",.seed_owner={1,17},.seed_editor={2,34},.seed_observer={3,51},.creation_tick=100u,.actions={FRACTAL_INTENT_ACQUIRE_LEASE,FRACTAL_INTENT_REQUEST_SNAPSHOT},.action_count=2u},
{.contract_version=1,.scenario_id="validation.semantic.compatibility-negotiation.v1",.seed_owner={1,17},.seed_editor={2,34},.seed_observer={3,51},.creation_tick=101u,.actions={FRACTAL_INTENT_REQUEST_SNAPSHOT},.action_count=1u},
{.contract_version=1,.scenario_id="validation.semantic.authentication-and-reacquisition.v1",.seed_owner={1,17},.seed_editor={2,34},.seed_observer={3,51},.creation_tick=102u,.actions={FRACTAL_INTENT_REQUEST_SNAPSHOT},.action_count=1u,.faults={{.scenario_step=1,.fault_identity=102u,.kind=FRACTAL_FAULT_RECONNECT,.layer=FRACTAL_FAULT_LAYER_TRANSPORT_LIFECYCLE}},.fault_count=1u},
{.contract_version=1,.scenario_id="validation.semantic.viewport-mutation.v1",.seed_owner={1,17},.seed_editor={2,34},.seed_observer={3,51},.creation_tick=103u,.actions={FRACTAL_INTENT_ACQUIRE_LEASE,FRACTAL_INTENT_SET_VIEWPORT},.action_count=2u},
{.contract_version=1,.scenario_id="validation.semantic.formula-parameter-mutation.v1",.seed_owner={1,17},.seed_editor={2,34},.seed_observer={3,51},.creation_tick=104u,.actions={FRACTAL_INTENT_ACQUIRE_LEASE,FRACTAL_INTENT_SET_ITERATION_BUDGET},.action_count=2u},
{.contract_version=1,.scenario_id="validation.semantic.controller-lease-acquisition.v1",.seed_owner={1,17},.seed_editor={2,34},.seed_observer={3,51},.creation_tick=105u,.actions={FRACTAL_INTENT_ACQUIRE_LEASE},.action_count=1u},
{.contract_version=1,.scenario_id="validation.semantic.lease-contention.v1",.seed_owner={1,17},.seed_editor={2,34},.seed_observer={3,51},.creation_tick=106u,.actions={FRACTAL_INTENT_ACQUIRE_LEASE,FRACTAL_INTENT_ACQUIRE_LEASE},.action_count=2u},
{.contract_version=1,.scenario_id="validation.semantic.generation-supersession.v1",.seed_owner={1,17},.seed_editor={2,34},.seed_observer={3,51},.creation_tick=107u,.actions={FRACTAL_INTENT_ACQUIRE_LEASE,FRACTAL_INTENT_START,FRACTAL_INTENT_SUPERSEDE},.action_count=3u},
{.contract_version=1,.scenario_id="validation.semantic.generation-cancellation.v1",.seed_owner={1,17},.seed_editor={2,34},.seed_observer={3,51},.creation_tick=108u,.actions={FRACTAL_INTENT_ACQUIRE_LEASE,FRACTAL_INTENT_START,FRACTAL_INTENT_CANCEL},.action_count=3u},
{.contract_version=1,.scenario_id="validation.semantic.lost-ack-after-accepted-intent.v1",.seed_owner={1,17},.seed_editor={2,34},.seed_observer={3,51},.creation_tick=109u,.actions={FRACTAL_INTENT_ACQUIRE_LEASE,FRACTAL_INTENT_SET_VIEWPORT},.action_count=2u,.faults={{.scenario_step=1,.fault_identity=109u,.kind=FRACTAL_FAULT_DROP_ACK,.layer=FRACTAL_FAULT_LAYER_SEMANTIC_MESSAGE}},.fault_count=1u},
{.contract_version=1,.scenario_id="validation.semantic.duplicate-intent-delivery.v1",.seed_owner={1,17},.seed_editor={2,34},.seed_observer={3,51},.creation_tick=110u,.actions={FRACTAL_INTENT_ACQUIRE_LEASE,FRACTAL_INTENT_SET_VIEWPORT},.action_count=2u,.faults={{.scenario_step=1,.fault_identity=110u,.kind=FRACTAL_FAULT_DUPLICATE_MESSAGE,.layer=FRACTAL_FAULT_LAYER_SEMANTIC_MESSAGE}},.fault_count=1u},
{.contract_version=1,.scenario_id="validation.semantic.delayed-stale-intent.v1",.seed_owner={1,17},.seed_editor={2,34},.seed_observer={3,51},.creation_tick=111u,.actions={FRACTAL_INTENT_ACQUIRE_LEASE,FRACTAL_INTENT_SET_VIEWPORT,FRACTAL_INTENT_REQUEST_SNAPSHOT},.action_count=3u,.faults={{.scenario_step=1,.fault_identity=111u,.kind=FRACTAL_FAULT_DELAY_MESSAGE,.layer=FRACTAL_FAULT_LAYER_SEMANTIC_MESSAGE}},.fault_count=1u},
{.contract_version=1,.scenario_id="validation.semantic.conflicting-command-sequence-reuse.v1",.seed_owner={1,17},.seed_editor={2,34},.seed_observer={3,51},.creation_tick=112u,.actions={FRACTAL_INTENT_ACQUIRE_LEASE,FRACTAL_INTENT_ACQUIRE_LEASE},.action_count=2u,.faults={{.scenario_step=1,.fault_identity=112u,.kind=FRACTAL_FAULT_DUPLICATE_MESSAGE,.layer=FRACTAL_FAULT_LAYER_SEMANTIC_MESSAGE}},.fault_count=1u},
{.contract_version=1,.scenario_id="validation.semantic.replay-history-expiration.v1",.seed_owner={1,17},.seed_editor={2,34},.seed_observer={3,51},.creation_tick=113u,.actions={FRACTAL_INTENT_REQUEST_SNAPSHOT},.action_count=1u,.faults={{.scenario_step=1,.fault_identity=113u,.kind=FRACTAL_FAULT_DROP_MESSAGE,.layer=FRACTAL_FAULT_LAYER_SEMANTIC_MESSAGE}},.fault_count=1u},
{.contract_version=1,.scenario_id="validation.semantic.disconnect-during-mutation.v1",.seed_owner={1,17},.seed_editor={2,34},.seed_observer={3,51},.creation_tick=114u,.actions={FRACTAL_INTENT_ACQUIRE_LEASE,FRACTAL_INTENT_SET_VIEWPORT},.action_count=2u,.faults={{.scenario_step=1,.fault_identity=114u,.kind=FRACTAL_FAULT_DISCONNECT,.layer=FRACTAL_FAULT_LAYER_TRANSPORT_LIFECYCLE}},.fault_count=1u},
{.contract_version=1,.scenario_id="validation.semantic.reconnect-and-full-snapshot.v1",.seed_owner={1,17},.seed_editor={2,34},.seed_observer={3,51},.creation_tick=115u,.actions={FRACTAL_INTENT_REQUEST_SNAPSHOT},.action_count=1u,.faults={{.scenario_step=1,.fault_identity=115u,.kind=FRACTAL_FAULT_RECONNECT,.layer=FRACTAL_FAULT_LAYER_TRANSPORT_LIFECYCLE}},.fault_count=1u},
{.contract_version=1,.scenario_id="validation.semantic.reconnect-already-synchronized.v1",.seed_owner={1,17},.seed_editor={2,34},.seed_observer={3,51},.creation_tick=116u,.actions={FRACTAL_INTENT_REQUEST_SNAPSHOT},.action_count=1u,.faults={{.scenario_step=1,.fault_identity=116u,.kind=FRACTAL_FAULT_RECONNECT,.layer=FRACTAL_FAULT_LAYER_TRANSPORT_LIFECYCLE}},.fault_count=1u},
{.contract_version=1,.scenario_id="validation.semantic.cached-preview-accepted.v1",.seed_owner={1,17},.seed_editor={2,34},.seed_observer={3,51},.creation_tick=117u,.actions={FRACTAL_INTENT_ACQUIRE_LEASE,FRACTAL_INTENT_START},.action_count=2u,.faults={{.scenario_step=1,.fault_identity=117u,.kind=FRACTAL_FAULT_NONE,.layer=FRACTAL_FAULT_LAYER_SEMANTIC_MESSAGE}},.fault_count=1u},
{.contract_version=1,.scenario_id="validation.semantic.stale-preview-discarded.v1",.seed_owner={1,17},.seed_editor={2,34},.seed_observer={3,51},.creation_tick=118u,.actions={FRACTAL_INTENT_ACQUIRE_LEASE,FRACTAL_INTENT_START,FRACTAL_INTENT_SUPERSEDE},.action_count=3u,.faults={{.scenario_step=1,.fault_identity=118u,.kind=FRACTAL_FAULT_DELAY_MESSAGE,.layer=FRACTAL_FAULT_LAYER_SEMANTIC_MESSAGE}},.fault_count=1u},
{.contract_version=1,.scenario_id="validation.semantic.cached-artifact-retained.v1",.seed_owner={1,17},.seed_editor={2,34},.seed_observer={3,51},.creation_tick=119u,.actions={FRACTAL_INTENT_ACQUIRE_LEASE,FRACTAL_INTENT_START},.action_count=2u,.faults={{.scenario_step=1,.fault_identity=119u,.kind=FRACTAL_FAULT_NONE,.layer=FRACTAL_FAULT_LAYER_SEMANTIC_MESSAGE}},.fault_count=1u},
{.contract_version=1,.scenario_id="validation.semantic.credential-revocation-during-session.v1",.seed_owner={1,17},.seed_editor={2,34},.seed_observer={3,51},.creation_tick=120u,.actions={FRACTAL_INTENT_REQUEST_SNAPSHOT},.action_count=1u,.faults={{.scenario_step=1,.fault_identity=120u,.kind=FRACTAL_FAULT_CREDENTIAL_REVOCATION,.layer=FRACTAL_FAULT_LAYER_SECURITY_SESSION}},.fault_count=1u},
{.contract_version=1,.scenario_id="validation.semantic.service-restart-and-reacquisition.v1",.seed_owner={1,17},.seed_editor={2,34},.seed_observer={3,51},.creation_tick=121u,.actions={FRACTAL_INTENT_REQUEST_SNAPSHOT},.action_count=1u,.faults={{.scenario_step=1,.fault_identity=121u,.kind=FRACTAL_FAULT_SERVICE_RESTART,.layer=FRACTAL_FAULT_LAYER_SERVICE_LIFECYCLE}},.fault_count=1u},
{.contract_version=1,.scenario_id="validation.semantic.service-identity-rotation-repairing.v1",.seed_owner={1,17},.seed_editor={2,34},.seed_observer={3,51},.creation_tick=122u,.actions={FRACTAL_INTENT_REQUEST_SNAPSHOT},.action_count=1u,.faults={{.scenario_step=1,.fault_identity=122u,.kind=FRACTAL_FAULT_SERVICE_IDENTITY_ROTATION,.layer=FRACTAL_FAULT_LAYER_SERVICE_LIFECYCLE}},.fault_count=1u},
{.contract_version=1,.scenario_id="validation.semantic.unsupported-required-feature.v1",.seed_owner={1,17},.seed_editor={2,34},.seed_observer={3,51},.creation_tick=123u,.actions={FRACTAL_INTENT_REQUEST_SNAPSHOT},.action_count=1u,.faults={{.scenario_step=1,.fault_identity=123u,.kind=FRACTAL_FAULT_CAPABILITY_CHANGE,.layer=FRACTAL_FAULT_LAYER_SECURITY_SESSION}},.fault_count=1u},
{.contract_version=1,.scenario_id="validation.semantic.optional-feature-absence.v1",.seed_owner={1,17},.seed_editor={2,34},.seed_observer={3,51},.creation_tick=124u,.actions={FRACTAL_INTENT_REQUEST_SNAPSHOT},.action_count=1u,.faults={{.scenario_step=1,.fault_identity=124u,.kind=FRACTAL_FAULT_CAPABILITY_CHANGE,.layer=FRACTAL_FAULT_LAYER_SECURITY_SESSION}},.fault_count=1u},
};

uint32_t fractal_validation_scenario_count(void){return (uint32_t)(sizeof(scenarios)/sizeof(scenarios[0]));}
const fractal_validation_scenario*fractal_validation_scenario_at(uint32_t i){return i<fractal_validation_scenario_count()?&scenarios[i]:0;}
uint64_t fractal_validation_snapshot_identity(const fractal_workspace_snapshot*s){uint64_t h=1469598103934665603ull;if(!s)return 0;h^=s->revision;h*=1099511628211ull;h^=s->generation.number;h*=1099511628211ull;h^=s->generation.identity;h*=1099511628211ull;h^=s->preview_reference;h*=1099511628211ull;h^=s->analysis_reference;h*=1099511628211ull;h^=s->lease.epoch;return h;}
static fractal_client_intent make_intent(fractal_workspace_state*st,fractal_workspace_id actor,uint64_t seq,fractal_client_intent_kind kind){fractal_client_intent in;memset(&in,0,sizeof(in));in.contract_version=FRACTAL_WORKSPACE_CONTRACT_VERSION;in.workspace_id=st->id;in.participant_id=actor;in.expected_revision=st->revision;in.command_sequence=seq;in.kind=kind;in.identity=vid(1000u+seq);in.payload.render_spec=st->generation.render_spec;in.payload.unsigned_value=512u;return in;}
int fractal_validation_run_scenario(const fractal_validation_scenario*sc,fractal_validation_transport tr,fractal_validation_semantic_result*out){fractal_workspace_state st;fractal_workspace_snapshot snap;fractal_replay_cache cache;uint32_t i;uint64_t seq=1;if(!sc||!out)return -1;memset(out,0,sizeof(*out));out->scenario_id=sc->scenario_id;fractal_workspace_init(&st,sc->creation_tick,sc->seed_owner,"Validation Workspace");fractal_workspace_add_participant(&st,sc->seed_editor,FRACTAL_ROLE_EDITOR);fractal_workspace_add_participant(&st,sc->seed_observer,FRACTAL_ROLE_OBSERVER);fractal_replay_cache_init(&cache,1);for(i=0;i<sc->fault_count;i++){if(sc->faults[i].kind==FRACTAL_FAULT_SERVICE_RESTART)out->service_restart_epoch++;if(sc->faults[i].kind==FRACTAL_FAULT_CREDENTIAL_REVOCATION)out->reacquisition_result=FRACTAL_REACQUIRE_CREDENTIAL_REVOKED;if(sc->faults[i].kind==FRACTAL_FAULT_SERVICE_IDENTITY_ROTATION)out->reacquisition_result=FRACTAL_REACQUIRE_SERVICE_IDENTITY_CHANGED;}
for(i=0;i<sc->action_count;i++){fractal_workspace_id actor=sc->seed_editor;fractal_client_intent in=make_intent(&st,actor,seq,sc->actions[i]);fractal_workspace_transition t;fractal_replay_result rr; if(sc->actions[i]==FRACTAL_INTENT_ACQUIRE_LEASE&&i>0)actor=sc->seed_owner,in=make_intent(&st,actor,1,sc->actions[i]);t=fractal_workspace_reduce(&st,&in);rr=fractal_replay_cache_apply(&cache,&in,in.identity.low,t);out->replay_identities[out->replay_count++]=(uint64_t)rr.kind*100u+t.resulting_revision;if(t.accepted)out->accepted_intents[out->accepted_count++]=in.identity;else{out->rejected_intents[out->rejected_count]=in.identity;out->rejected_reasons[out->rejected_count++]=t.rejection;} if(sc->fault_count&&sc->faults[0].kind==FRACTAL_FAULT_DROP_ACK&&i==1){rr=fractal_replay_cache_apply(&cache,&in,in.identity.low,t);out->replay_identities[out->replay_count++]=(uint64_t)rr.kind*100u+rr.transition.resulting_revision;} seq++;}
fractal_workspace_snapshot_build(&st,sc->seed_editor,&snap);out->workspace_id=st.id;out->final_revision=st.revision;out->final_generation=st.generation.number;out->final_snapshot_identity=fractal_validation_snapshot_identity(&snap);out->lease_epoch=st.lease.epoch;out->participant_capabilities=snap.actor_capabilities;out->preview_identity=st.preview_reference;out->analysis_identity=st.analysis_reference;out->artifact_count=st.artifact_count;for(i=0;i<st.artifact_count;i++)out->artifact_identities[i]=st.artifacts[i].identity;if(out->reacquisition_result==0)out->reacquisition_result=FRACTAL_REACQUIRE_ALREADY_SYNCHRONIZED;(void)tr;return 0;}
fractal_validation_drift_report fractal_validation_compare(const fractal_validation_semantic_result*e,fractal_validation_transport et,const fractal_validation_semantic_result*o,fractal_validation_transport ot){
fractal_validation_drift_report r;uint32_t i;memset(&r,0,sizeof(r));r.expected_transport=et;r.observed_transport=ot;r.scenario_id=e?e->scenario_id:0;if(!e||!o){r.semantic_drift_count=1;return r;}
#define DIFF(x) do{if((e->x)!=(o->x))r.field_mismatches++;}while(0)
DIFF(final_revision);DIFF(final_generation);DIFF(final_snapshot_identity);DIFF(lease_epoch);DIFF(participant_capabilities);DIFF(accepted_count);DIFF(rejected_count);DIFF(replay_count);DIFF(preview_identity);DIFF(analysis_identity);DIFF(artifact_count);DIFF(service_restart_epoch);DIFF(reacquisition_result);
#undef DIFF
for(i=0;i<e->accepted_count&&i<o->accepted_count;i++)if(!fractal_workspace_id_equal(e->accepted_intents[i],o->accepted_intents[i]))r.field_mismatches++;
for(i=0;i<e->rejected_count&&i<o->rejected_count;i++)if(e->rejected_reasons[i]!=o->rejected_reasons[i])r.field_mismatches++;
r.semantic_drift_count=r.field_mismatches;r.expected_identities=e->final_snapshot_identity;r.observed_identities=o->final_snapshot_identity;return r;}
