#include "fractal/workspace_controller.h"
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
static uint64_t hbytes(uint64_t h,const void*p,size_t n){const unsigned char*b=(const unsigned char*)p;for(size_t i=0;i<n;i++){h^=b[i];h*=UINT64_C(1099511628211);}return h;}
static fractal_intent_id cmd_id(uint64_t n){fractal_intent_id id={UINT64_C(0x4354524c00000000),n};return id;}
const char*fractal_controller_state_name(fractal_controller_state s){static const char*n[]={"DISCONNECTED","CONNECTING","SYNCHRONIZING","READY","EDITING","SUBMITTING","RENDERING","ANALYZING","PUBLISHING","COMPLETE","CANCELLING","FAILED"};return s<=FRACTAL_CONTROLLER_FAILED?n[s]:"FAILED";}
const char*fractal_runtime_stage_name(fractal_runtime_stage s){static const char*n[]={"IDLE","QUEUED","PREPARING","RENDERING","ANALYSIS_PENDING","ANALYZING","PUBLISHING","COMPLETED","CANCELLING","CANCELLED","FAILED","SUPERSEDED"};return s<=FRACTAL_RUNTIME_SUPERSEDED?n[s]:"FAILED";}
const char*fractal_analysis_policy_name(fractal_analysis_policy p){static const char*n[]={"OFF","CHECKPOINT","DEFERRED"};return p<=FRACTAL_ANALYSIS_DEFERRED?n[p]:"OFF";}
const char*fractal_analysis_state_name(fractal_analysis_state s){static const char*n[]={"NOT_REQUESTED","PENDING","WAITING_FOR_IDLE","RUNNING","COMPLETED","CANCELLED","SUPERSEDED","FAILED"};return s<=FRACTAL_ANALYSIS_FAILED?n[s]:"FAILED";}
static uint64_t config_identity(const fractal_render_configuration*c){fractal_render_configuration t=*c;t.identity=0;t.checksum=0;return hbytes(UINT64_C(1469598103934665603),&t,sizeof(t));}
int fractal_render_configuration_default(fractal_render_configuration*c){if(!c)return-1;memset(c,0,sizeof(*c));c->version=FRACTAL_RENDER_CONFIGURATION_VERSION;fractal_render_spec_init_default(&c->render_spec);strcpy(c->formula_id,"fractal.formula.mandelbrot.v1");strcpy(c->numeric_id,"fractal.numeric.binary64.v1");c->iteration_budget=64;c->bailout=4.0;strcpy(c->scheduler_id,"fractal.scheduler.serial.v1");strcpy(c->analyzer_ids[0],"fractal.analyzer.escape-summary.v1");strcpy(c->analyzer_ids[1],"fractal.analyzer.spatial-grid.v1");c->analyzer_count=2;c->output_policy=1;c->identity=config_identity(c);c->checksum=hbytes(UINT64_C(1099511628211),c,sizeof(*c)-sizeof(c->checksum));return 0;}
int fractal_render_configuration_validate(const fractal_render_configuration*c){if(!c||c->version!=FRACTAL_RENDER_CONFIGURATION_VERSION||c->analyzer_count>FRACTAL_RENDER_CONFIGURATION_MAX_ANALYZERS)return-1;if(fractal_render_spec_validate(&c->render_spec)!=FRACTAL_OK)return-1;fractal_render_configuration t=*c;uint64_t chk,ident=t.identity;t.checksum=0;t.identity=0;if(ident!=config_identity(c))return-1;chk=hbytes(UINT64_C(1099511628211),c,sizeof(*c)-sizeof(c->checksum));return chk==c->checksum?0:-1;}
static int safe_dir(const char*d){return d&&strstr(d,"..")==NULL&&strlen(d)<160;}
int fractal_render_configuration_save_local(const fractal_render_configuration*c,const char*d,char*out,size_t cap){char path[256],tmp[280];FILE*f;if(fractal_render_configuration_validate(c)!=0||!safe_dir(d))return-1;mkdir(d,0700);snprintf(path,sizeof(path),"%s/config_%016llx.frcfg",d,(unsigned long long)c->identity);snprintf(tmp,sizeof(tmp),"%s.tmp",path);f=fopen(tmp,"wb");if(!f)return-1;if(fwrite(c,1,sizeof(*c),f)!=sizeof(*c)){fclose(f);unlink(tmp);return-1;}fclose(f);if(rename(tmp,path)!=0){unlink(tmp);return-1;}if(out&&cap>0)snprintf(out,cap,"config_%016llx.frcfg",(unsigned long long)c->identity);return 0;}
int fractal_render_configuration_load_local(fractal_render_configuration*c,const char*d,uint64_t id){char path[256];FILE*f;if(!c||!safe_dir(d))return-1;snprintf(path,sizeof(path),"%s/config_%016llx.frcfg",d,(unsigned long long)id);f=fopen(path,"rb");if(!f)return-1;if(fread(c,1,sizeof(*c),f)!=sizeof(*c)){fclose(f);return-1;}fclose(f);return fractal_render_configuration_validate(c);}
static fractal_client_intent mk(fractal_workspace_controller*c,fractal_client_intent_kind k){fractal_client_intent i;memset(&i,0,sizeof(i));i.contract_version=FRACTAL_WORKSPACE_CONTRACT_VERSION;i.workspace_id=c->service.workspace.id;i.participant_id=c->participant;i.expected_revision=c->service.workspace.revision;i.command_sequence=c->next_command_sequence++;i.kind=k;i.identity=cmd_id(i.command_sequence);return i;}
int fractal_workspace_controller_init(fractal_workspace_controller*c,fractal_analysis_policy p){if(!c)return-1;memset(c,0,sizeof(*c));c->state=FRACTAL_CONTROLLER_CONNECTING;fractal_local_service_init(&c->service,1);if(fractal_local_service_open(&c->service)!=0)return-1;c->state=FRACTAL_CONTROLLER_SYNCHRONIZING;if(fractal_local_service_open_session(&c->service,fractal_local_operator_admit_current_user(),&c->participant)!=0)return-1;c->next_command_sequence=1;c->state=FRACTAL_CONTROLLER_READY;fractal_render_configuration_default(&c->configuration);c->analysis.policy=p;c->analysis.state=FRACTAL_ANALYSIS_NOT_REQUESTED;c->progress.stage=FRACTAL_RUNTIME_IDLE;return 0;}
int fractal_workspace_controller_apply_configuration(fractal_workspace_controller*c,const fractal_render_configuration*cfg){fractal_client_intent i;if(!c||fractal_render_configuration_validate(cfg)!=0)return-1;c->state=FRACTAL_CONTROLLER_EDITING;c->configuration=*cfg;i=mk(c,FRACTAL_INTENT_ACQUIRE_LEASE);fractal_local_service_apply_intent(&c->service,&i);i=mk(c,FRACTAL_INTENT_SET_VIEWPORT);i.payload.render_spec=cfg->render_spec;if(!fractal_local_service_apply_intent(&c->service,&i).transition.accepted)return-1;c->state=FRACTAL_CONTROLLER_READY;return 0;}
int fractal_workspace_controller_start(fractal_workspace_controller*c){fractal_client_intent i;if(!c)return-1;c->state=FRACTAL_CONTROLLER_SUBMITTING;i=mk(c,FRACTAL_INTENT_START);if(!fractal_local_service_apply_intent(&c->service,&i).transition.accepted)return-1;c->progress.workspace_id=c->service.workspace.id;c->progress.generation=c->service.workspace.generation.number;c->progress.stage=FRACTAL_RUNTIME_QUEUED;c->progress.total_work_units=4;c->progress.completed_work_units=0;c->progress.rows_completed=0;c->analysis.workspace_id=c->service.workspace.id;c->analysis.generation=c->progress.generation;c->analysis.field_identity=c->service.workspace.generation.identity;c->analysis.analyzer_chain_identity=hbytes(UINT64_C(1469598103934665603),c->configuration.analyzer_ids,sizeof(c->configuration.analyzer_ids));c->analysis.state=c->analysis.policy==FRACTAL_ANALYSIS_OFF?FRACTAL_ANALYSIS_NOT_REQUESTED:FRACTAL_ANALYSIS_PENDING;c->cost.jobs_requested+=c->analysis.policy==FRACTAL_ANALYSIS_OFF?0u:1u;c->state=FRACTAL_CONTROLLER_RENDERING;return 0;}
static void publish(fractal_workspace_controller*c){uint64_t g=c->progress.generation;c->progress.stage=FRACTAL_RUNTIME_PUBLISHING;c->preview.workspace_id=c->service.workspace.id;c->preview.generation=g;c->preview.preview_sequence++;c->preview.completeness_basis_points=10000;c->preview.width=c->configuration.render_spec.image_width;c->preview.height=c->configuration.render_spec.image_height;c->preview.source_field_revision=c->service.workspace.revision;c->preview.preview_identity=hbytes(g,&c->preview,sizeof(c->preview)-sizeof(c->preview.preview_identity));c->artifact_identity=hbytes(UINT64_C(0x415254),&g,sizeof(g));c->service.workspace.preview_reference=c->preview.preview_identity;c->service.workspace.artifacts[0].generation=g;c->service.workspace.artifacts[0].identity=c->artifact_identity;strcpy(c->service.workspace.artifacts[0].name,"local-reference-artifact");c->service.workspace.artifact_count=1;c->progress.artifact_published=true;c->progress.stage=FRACTAL_RUNTIME_COMPLETED;if(c->analysis.policy==FRACTAL_ANALYSIS_CHECKPOINT){c->state=FRACTAL_CONTROLLER_ANALYZING;c->analysis.state=FRACTAL_ANALYSIS_RUNNING;c->analysis.result_identity=hbytes(UINT64_C(0x414e41),&c->analysis,sizeof(c->analysis)-sizeof(c->analysis.checkpoint_identity));c->analysis.artifact_identity=c->artifact_identity;c->analysis.state=FRACTAL_ANALYSIS_COMPLETED;c->cost.jobs_completed++;c->cost.analyzer_elapsed_ticks+=2;c->service.workspace.analysis_reference=c->analysis.result_identity;}else if(c->analysis.policy==FRACTAL_ANALYSIS_DEFERRED){c->analysis.state=FRACTAL_ANALYSIS_WAITING_FOR_IDLE;c->progress.stage=FRACTAL_RUNTIME_ANALYSIS_PENDING;}c->state=FRACTAL_CONTROLLER_COMPLETE;}
int fractal_workspace_controller_wait(fractal_workspace_controller*c,uint32_t ticks){if(!c)return-1;for(uint32_t t=0;t<ticks;t++){if(c->progress.stage==FRACTAL_RUNTIME_QUEUED)c->progress.stage=FRACTAL_RUNTIME_PREPARING;else if(c->progress.stage==FRACTAL_RUNTIME_PREPARING)c->progress.stage=FRACTAL_RUNTIME_RENDERING;else if(c->progress.stage==FRACTAL_RUNTIME_RENDERING){c->progress.completed_work_units++;c->progress.rows_completed+=8;c->cost.render_elapsed_ticks++;c->preview.preview_sequence++;c->progress.latest_preview_sequence=c->preview.preview_sequence;if(c->progress.completed_work_units>=c->progress.total_work_units)publish(c);}else if(c->analysis.state==FRACTAL_ANALYSIS_WAITING_FOR_IDLE){c->analysis.idle_ticks_observed++;if(c->analysis.idle_ticks_observed>=2){c->state=FRACTAL_CONTROLLER_ANALYZING;c->progress.stage=FRACTAL_RUNTIME_ANALYZING;c->analysis.state=FRACTAL_ANALYSIS_COMPLETED;c->analysis.result_identity=hbytes(UINT64_C(0x44454641),&c->analysis,sizeof(c->analysis)-sizeof(c->analysis.checkpoint_identity));c->service.workspace.analysis_reference=c->analysis.result_identity;c->cost.jobs_completed++;c->cost.analyzer_elapsed_ticks+=2;c->progress.stage=FRACTAL_RUNTIME_COMPLETED;c->state=FRACTAL_CONTROLLER_COMPLETE;}}}c->progress.progress_identity=hbytes(UINT64_C(0x50524f47),&c->progress,sizeof(c->progress)-sizeof(c->progress.progress_identity));if(c->cost.render_elapsed_ticks)c->cost.analysis_to_render_ratio_basis_points=(uint32_t)((c->cost.analyzer_elapsed_ticks*10000u)/c->cost.render_elapsed_ticks);c->cost.selected_analyzer_count=c->configuration.analyzer_count;return 0;}
int fractal_workspace_controller_cancel(fractal_workspace_controller*c){if(!c)return-1;c->state=FRACTAL_CONTROLLER_CANCELLING;c->progress.cancellation_requested=true;c->progress.stage=FRACTAL_RUNTIME_CANCELLED;if(c->analysis.state==FRACTAL_ANALYSIS_PENDING||c->analysis.state==FRACTAL_ANALYSIS_WAITING_FOR_IDLE){c->analysis.state=FRACTAL_ANALYSIS_CANCELLED;c->cost.jobs_skipped++;}c->state=FRACTAL_CONTROLLER_COMPLETE;return 0;}
int fractal_workspace_controller_rapid_edit(fractal_workspace_controller*c,uint32_t edits){fractal_client_intent i;if(!c)return-1;for(uint32_t e=0;e<edits;e++){uint64_t old=c->progress.generation;i=mk(c,FRACTAL_INTENT_SET_ITERATION_BUDGET);i.payload.unsigned_value=64u+e;if(!fractal_local_service_apply_intent(&c->service,&i).transition.accepted)return-1;if(old&&old!=c->service.workspace.generation.number){c->preview.stale_or_superseded=true;if(c->analysis.state==FRACTAL_ANALYSIS_PENDING||c->analysis.state==FRACTAL_ANALYSIS_WAITING_FOR_IDLE){c->analysis.state=FRACTAL_ANALYSIS_SUPERSEDED;c->cost.jobs_cancelled_by_supersession++;}}}return fractal_workspace_controller_start(c);}
fractal_controller_summary fractal_workspace_controller_summary(const fractal_workspace_controller*c){fractal_controller_summary s;memset(&s,0,sizeof(s));if(!c)return s;s.controller_state=c->state;s.workspace_revision=c->service.workspace.revision;s.generation=c->service.workspace.generation.number;s.runtime_stage=c->progress.stage;s.completed_work_units=c->progress.completed_work_units;s.total_work_units=c->progress.total_work_units;s.preview_identity=c->preview.preview_identity;s.analysis_state=c->analysis.state;s.analysis_identity=c->analysis.result_identity;s.artifact_identity=c->artifact_identity;s.semantic_drift=c->semantic_drift;s.error_status=c->progress.error_status;return s;}
int fractal_workspace_controller_run_reference(fractal_analysis_policy p,fractal_controller_summary*out){fractal_workspace_controller c;if(!out)return-1;if(fractal_workspace_controller_init(&c,p)!=0)return-1;if(fractal_workspace_controller_apply_configuration(&c,&c.configuration)!=0)return-1;if(fractal_workspace_controller_start(&c)!=0)return-1;if(fractal_workspace_controller_wait(&c,8)!=0)return-1;*out=fractal_workspace_controller_summary(&c);return 0;}
