#ifndef FRACTAL_FAKE_TRANSPORT_H
#define FRACTAL_FAKE_TRANSPORT_H
#include "fractal/platform_services.h"
#define FRACTAL_FAKE_TRANSPORT_EVENT_CAPACITY 16u
typedef enum fractal_fake_transport_event{FRACTAL_FAKE_CONNECTION_ESTABLISHED=0,FRACTAL_FAKE_CONNECTION_DROPPED,FRACTAL_FAKE_MESSAGE_DELIVERED,FRACTAL_FAKE_MESSAGE_DUPLICATED,FRACTAL_FAKE_MESSAGE_DELAYED,FRACTAL_FAKE_ACK_LOST,FRACTAL_FAKE_SERVICE_RESTART,FRACTAL_FAKE_NETWORK_CHANGED,FRACTAL_FAKE_CLIENT_SUSPENDED,FRACTAL_FAKE_CLIENT_RESUMED,FRACTAL_FAKE_COMPATIBILITY_MISMATCH,FRACTAL_FAKE_REVOCATION}fractal_fake_transport_event;
typedef struct fractal_fake_transport{fractal_fake_transport_event events[FRACTAL_FAKE_TRANSPORT_EVENT_CAPACITY];uint32_t count;uint32_t cursor;fractal_transport_status status;uint64_t service_restart_epoch;bool revoked;bool compatibility_mismatch;bool ack_lost;}fractal_fake_transport;
void fractal_fake_transport_init(fractal_fake_transport*transport);
int fractal_fake_transport_push(fractal_fake_transport*transport,fractal_fake_transport_event event);
int fractal_fake_transport_step(fractal_fake_transport*transport,fractal_fake_transport_event*out);
#endif
