#ifndef FRACTAL_COMPATIBILITY_H
#define FRACTAL_COMPATIBILITY_H
#include <stdbool.h>
#include <stdint.h>
#include "fractal/pairing.h"
#ifdef __cplusplus
extern "C" {
#endif
#define FRACTAL_COMPATIBILITY_CONTRACT_VERSION 1u
#define FRACTAL_FEATURE_CAPACITY 16u
#define FRACTAL_BUILD_ID_CAPACITY 48u
typedef enum fractal_platform_class{FRACTAL_PLATFORM_DESKTOP=0,FRACTAL_PLATFORM_ANDROID,FRACTAL_PLATFORM_BACKEND_LINUX,FRACTAL_PLATFORM_BACKEND_WINDOWS,FRACTAL_PLATFORM_TEST}fractal_platform_class;
typedef enum fractal_feature_id{FRACTAL_FEATURE_WORKSPACE_HISTORY=1,FRACTAL_FEATURE_PREVIEW_FULL_FRAME,FRACTAL_FEATURE_PREVIEW_TILE,FRACTAL_FEATURE_ANALYSIS_SUMMARY,FRACTAL_FEATURE_ANALYSIS_HISTOGRAM,FRACTAL_FEATURE_ARTIFACT_BMP,FRACTAL_FEATURE_CONTROLLER_LEASE,FRACTAL_FEATURE_PAIRING_ATTESTATION}fractal_feature_id;
typedef struct fractal_feature{fractal_feature_id id;uint32_t version;bool required;}fractal_feature;
typedef struct fractal_version_range{uint32_t minimum;uint32_t maximum;}fractal_version_range;
typedef struct fractal_compatibility_client_hello{uint32_t contract_version;fractal_version_range protocol_family;fractal_version_range message_schema;fractal_version_range workspace_contract;fractal_version_range pairing_contract;fractal_feature features[FRACTAL_FEATURE_CAPACITY];uint32_t feature_count;char client_build_identity[FRACTAL_BUILD_ID_CAPACITY];fractal_platform_class platform_class;fractal_service_id cached_service_identity;uint64_t last_known_service_compatibility_epoch;}fractal_compatibility_client_hello;
typedef struct fractal_compatibility_service_hello{uint32_t contract_version;fractal_version_range protocol_family;fractal_version_range message_schema;fractal_version_range workspace_contract;fractal_version_range pairing_contract;uint32_t service_capability_version;uint32_t minimum_supported_client_contract;fractal_feature features[FRACTAL_FEATURE_CAPACITY];uint32_t feature_count;fractal_feature deprecated_features[FRACTAL_FEATURE_CAPACITY];uint32_t deprecated_feature_count;bool client_upgrade_required;bool service_upgrade_required;uint64_t service_compatibility_epoch;uint64_t service_restart_epoch;}fractal_compatibility_service_hello;
typedef enum fractal_compatibility_result{FRACTAL_COMPATIBLE=0,FRACTAL_COMPATIBLE_WITH_DEPRECATIONS,FRACTAL_CLIENT_UPGRADE_REQUIRED,FRACTAL_SERVICE_UPGRADE_REQUIRED,FRACTAL_NO_COMMON_PROTOCOL,FRACTAL_NO_COMMON_SCHEMA,FRACTAL_NO_COMMON_WORKSPACE_CONTRACT,FRACTAL_NO_COMMON_PAIRING_CONTRACT,FRACTAL_CAPABILITY_MISMATCH}fractal_compatibility_result;
typedef struct fractal_compatibility_selection{fractal_compatibility_result result;uint32_t selected_protocol_family;uint32_t selected_schema_version;uint32_t selected_workspace_contract;uint32_t selected_pairing_contract;fractal_feature features[FRACTAL_FEATURE_CAPACITY];uint32_t feature_count;uint64_t service_compatibility_epoch;uint64_t service_restart_epoch;}fractal_compatibility_selection;
fractal_compatibility_selection fractal_compatibility_negotiate(const fractal_compatibility_client_hello*client,const fractal_compatibility_service_hello*service);
#ifdef __cplusplus
}
#endif
#endif
