#ifndef FRACTAL_REACQUIRE_H
#define FRACTAL_REACQUIRE_H
#include <stdbool.h>
#include <stdint.h>
#include "fractal/compatibility.h"
#ifdef __cplusplus
extern "C" {
#endif
#define FRACTAL_REACQUIRE_CONTRACT_VERSION 1u
typedef enum fractal_preview_mode{FRACTAL_PREVIEW_NONE=0,FRACTAL_PREVIEW_FULL_FRAME,FRACTAL_PREVIEW_TILED,FRACTAL_PREVIEW_PROGRESSIVE}fractal_preview_mode;
typedef struct fractal_reacquire_request{uint32_t contract_version;fractal_service_id service_id;fractal_participant_id participant_id;fractal_device_id device_id;fractal_credential_id credential_id;fractal_workspace_id workspace_id;uint64_t last_accepted_workspace_revision;uint64_t last_known_generation;uint64_t last_accepted_command_sequence;fractal_intent_id last_acknowledged_intent_identity;uint64_t last_preview_generation;uint64_t last_preview_identity;uint64_t last_preview_checksum;uint64_t last_analysis_revision;uint64_t last_artifact_history_revision;fractal_compatibility_selection client_compatibility_selection;uint64_t session_epoch;uint64_t freshness_tick;}fractal_reacquire_request;
typedef enum fractal_reacquire_response_kind{FRACTAL_REACQUIRE_FULL_SNAPSHOT=0,FRACTAL_REACQUIRE_BOUNDED_DELTA,FRACTAL_REACQUIRE_ALREADY_SYNCHRONIZED,FRACTAL_REACQUIRE_WORKSPACE_NOT_FOUND,FRACTAL_REACQUIRE_WORKSPACE_ACCESS_REVOKED,FRACTAL_REACQUIRE_CREDENTIAL_REVOKED,FRACTAL_REACQUIRE_SERVICE_IDENTITY_CHANGED,FRACTAL_REACQUIRE_REPAIRING_REQUIRED,FRACTAL_REACQUIRE_CLIENT_UPGRADE_REQUIRED}fractal_reacquire_response_kind;
typedef struct fractal_replay_cache_summary{uint64_t first_retained_sequence;uint64_t latest_sequence;uint32_t retained_count;}fractal_replay_cache_summary;
typedef struct fractal_reacquire_response{uint32_t contract_version;fractal_reacquire_response_kind kind;uint64_t current_workspace_revision;uint64_t current_generation;uint64_t service_restart_epoch;uint64_t latest_accepted_client_command_sequence;fractal_replay_cache_summary replay_cache;fractal_workspace_capabilities capability_set;fractal_controller_lease controller_lease;fractal_preview_mode preview_mode;uint64_t preview_identity;uint64_t preview_checksum;uint64_t analysis_revision;uint64_t artifact_history_revision;fractal_workspace_snapshot snapshot;uint64_t deterministic_reacquisition_identity;}fractal_reacquire_response;
typedef enum fractal_reacquire_state{FRACTAL_REACQUIRE_IDLE=0,FRACTAL_REACQUIRE_REQUESTED,FRACTAL_REACQUIRE_SYNCHRONIZED,FRACTAL_REACQUIRE_BLOCKED}fractal_reacquire_state;
typedef struct fractal_reacquire_transition{bool accepted;fractal_reacquire_state state;fractal_reacquire_response_kind response_kind;}fractal_reacquire_transition;
fractal_reacquire_transition fractal_reacquire_reduce(fractal_reacquire_state state,const fractal_reacquire_response*response);
bool fractal_preview_cache_valid(uint64_t cached_generation,uint64_t cached_identity,uint64_t cached_checksum,const fractal_reacquire_response*response);
bool fractal_artifact_cache_valid(uint64_t cached_identity,uint64_t cached_checksum,uint64_t authoritative_identity,uint64_t authoritative_checksum);
#ifdef __cplusplus
}
#endif
#endif
