#include "fractal/socketable_runtime.h"
#include <stdio.h>
#include <string.h>
static int failures;
#define CHECK(x) do{if(!(x)){fprintf(stderr,"%s:%d: %s\n",__FILE__,__LINE__,#x);failures++;}}while(0)
typedef struct buffer { unsigned char data[65536]; size_t used; } buffer;
static fractal_result write_buffer(void *v,const void *data,size_t n){buffer*b=v;if(n>sizeof(b->data)-b->used)return FRACTAL_ERROR_BUFFER_TOO_SMALL;memcpy(b->data+b->used,data,n);b->used+=n;return FRACTAL_OK;}
static fractal_runtime_modules modules(fractal_memory_backend*m,const fractal_formula_vtable*f){fractal_runtime_modules r={f,&fractal_numeric_binary64,&fractal_compute_conventional,&fractal_refinement_none,&fractal_scheduler_serial,&fractal_raster_native,&fractal_encoder_bmp,&fractal_memory_system_module,m,&fractal_telemetry_noop,NULL,&fractal_platform_host};return r;}
static void metadata(void){fractal_module_descriptor bad=*fractal_formula_mandelbrot.descriptor;CHECK(!strcmp(bad.module_id,"formula.mandelbrot.quadratic"));CHECK(fractal_module_descriptor_validate(&bad,FRACTAL_MODULE_FORMULA)==FRACTAL_OK);bad.abi_version=99;CHECK(fractal_module_descriptor_validate(&bad,FRACTAL_MODULE_FORMULA)==FRACTAL_ERROR_INVALID_SPEC);bad=*fractal_formula_mandelbrot.descriptor;bad.kind=(fractal_module_kind)99;CHECK(fractal_module_descriptor_validate(&bad,FRACTAL_MODULE_FORMULA)==FRACTAL_ERROR_INVALID_SPEC);}
static void formulas(void){fractal_mandelbrot_parameters mp={2};fractal_julia_parameters jp={-0.8,0.156,2};fractal_formula_parameters m={"formula.mandelbrot.quadratic",&mp,sizeof(mp)},j={"formula.julia.quadratic",&jp,sizeof(jp)};fractal_complex_state s;fractal_point_class c;double v;CHECK(fractal_formula_mandelbrot.initialize_state(&fractal_numeric_binary64,&m,2,0,&s)==FRACTAL_OK);fractal_numeric_binary64.to_double(&s.zr,&v);CHECK(v==0);fractal_formula_mandelbrot.step(&fractal_numeric_binary64,&s);fractal_numeric_binary64.to_double(&s.zr,&v);CHECK(v==2);CHECK(fractal_formula_julia.initialize_state(&fractal_numeric_binary64,&j,2,0,&s)==FRACTAL_OK);fractal_numeric_binary64.to_double(&s.zr,&v);CHECK(v==2);CHECK(fractal_formula_julia.step(&fractal_numeric_binary64,&s)==FRACTAL_OK);CHECK(fractal_formula_julia.classify(&fractal_numeric_binary64,&s,&c)==FRACTAL_OK&&c==FRACTAL_CLASS_ESCAPED);jp.escape_radius=-1;CHECK(fractal_formula_julia.validate_parameters(&j)==FRACTAL_ERROR_INVALID_SPEC);}
static uint64_t render(const fractal_formula_vtable*f,const fractal_formula_parameters*p,uint64_t*field,uint64_t*pixel,size_t*bytes){fractal_memory_backend mem;fractal_runtime_modules r;fractal_job_spec j={{f->descriptor->module_id,*p,64},{-0.5,0,3,32,24},{"palette.socket-v1",FRACTAL_PIXEL_BGR8},{"encoder.bmp.v3","fixture.bmp"}};fractal_runtime_output o;buffer b={{0},0};fractal_write_sink sink={&b,write_buffer};char manifest[2048];size_t n;CHECK(fractal_memory_backend_init_system(&mem)==FRACTAL_OK);r=modules(&mem,f);CHECK(fractal_runtime_validate(&r)==FRACTAL_OK);CHECK(fractal_runtime_render(&r,&j,&sink,NULL,&o)==FRACTAL_OK);CHECK(b.data[0]=='B'&&b.data[1]=='M'&&b.used==o.artifact_bytes);CHECK(o.field.samples==NULL&&o.pixels.pixels==NULL);CHECK(fractal_runtime_manifest(&r,&j,&o,manifest,sizeof(manifest),&n)==FRACTAL_OK);CHECK(strstr(manifest,"cdc")==NULL&&strstr(manifest,"ouro")==NULL&&strstr(manifest,f->descriptor->module_id)!=NULL);*field=o.field_checksum;*pixel=o.pixel_checksum;*bytes=o.artifact_bytes;fractal_memory_backend_shutdown(&mem);return o.artifact_checksum;}
static void assembly_and_render(void){fractal_memory_backend mem;fractal_runtime_modules r;fractal_mandelbrot_parameters mp={2};fractal_julia_parameters jp={-0.8,0.156,2};fractal_formula_parameters m={"formula.mandelbrot.quadratic",&mp,sizeof(mp)},j={"formula.julia.quadratic",&jp,sizeof(jp)};uint64_t mf,mpx,jf,jpx,ma,ja;size_t mb,jb;fractal_memory_backend_init_system(&mem);r=modules(&mem,&fractal_formula_mandelbrot);r.encoder=NULL;CHECK(fractal_runtime_validate(&r)==FRACTAL_ERROR_INVALID_ARGUMENT);r=modules(&mem,&fractal_formula_mandelbrot);r.refinement=&fractal_refinement_cdc_unavailable;CHECK(fractal_runtime_validate(&r)==FRACTAL_ERROR_NOT_IMPLEMENTED);r=modules(&mem,&fractal_formula_mandelbrot);r.memory_module=&fractal_memory_ouro_unavailable_module;CHECK(fractal_runtime_validate(&r)==FRACTAL_ERROR_NOT_IMPLEMENTED);ma=render(&fractal_formula_mandelbrot,&m,&mf,&mpx,&mb);ja=render(&fractal_formula_julia,&j,&jf,&jpx,&jb);CHECK(mf==UINT64_C(0x99ec88c2a0f8bac3)&&mpx==UINT64_C(0x4866aacc38290b5f)&&ma==UINT64_C(0xfb1a83bd5ca28e5f));CHECK(jf==UINT64_C(0x0fb4458e08bad6e1)&&jpx==UINT64_C(0xb272f08b0bbdca2b)&&ja==UINT64_C(0x4d4aa95bd137ec87));CHECK(ma!=ja&&mf!=jf&&mpx!=jpx&&mb==2358u&&mb==jb);printf("mandelbrot field=%016llx pixel=%016llx artifact=%016llx bytes=%zu\n",(unsigned long long)mf,(unsigned long long)mpx,(unsigned long long)ma,mb);printf("julia field=%016llx pixel=%016llx artifact=%016llx bytes=%zu\n",(unsigned long long)jf,(unsigned long long)jpx,(unsigned long long)ja,jb);fractal_memory_backend_shutdown(&mem);}
int main(void){metadata();formulas();assembly_and_render();return failures?1:0;}
