#include "fractal/pairing.h"
#include <assert.h>
#include <stdio.h>
#include <string.h>

static fractal_workspace_id idv(uint64_t v) { fractal_workspace_id id = {v, v ^ UINT64_C(0xabcdef)}; return id; }
static fractal_pairing_nonce nonce(uint8_t seed) { fractal_pairing_nonce n; uint32_t i; for (i = 0u; i < FRACTAL_PAIRING_NONCE_CAPACITY; ++i) n.bytes[i] = (uint8_t)(seed + i); return n; }
static fractal_service_identity service(void) { fractal_service_identity s; memset(&s, 0, sizeof(s)); s.id = idv(10u); strcpy(s.display_name, "Local Studio"); s.identity_version = 1u; s.key_version = 7u; s.created_tick = 100u; s.status = FRACTAL_IDENTITY_CURRENT; return s; }
static fractal_pairing_invitation invitation(void) { return fractal_pairing_invitation_create(idv(10u), 7u, FRACTAL_ROLE_EDITOR, fractal_workspace_role_capabilities(FRACTAL_ROLE_EDITOR), 100u, 200u, nonce(1u), 424242u); }
static void msg(fractal_pairing_message *m, fractal_pairing_message_kind kind, fractal_pairing_state *s, uint64_t seq, uint8_t n) { memset(m, 0, sizeof(*m)); m->protocol_version = FRACTAL_PAIRING_PROTOCOL_VERSION; m->kind = kind; m->handshake_id = idv(99u); m->service_id = idv(10u); m->device_id = idv(20u); m->invitation_id = s->invitation.id; m->previous_transcript = s->transcript; m->sequence = seq; m->expires_tick = 190u; m->nonce = nonce(n); m->identity = fractal_pairing_message_identity(m); }
static fractal_pairing_transition step(fractal_pairing_state *s, fractal_pairing_message_kind kind, uint64_t seq, uint8_t n) { fractal_pairing_message m; msg(&m, kind, s, seq, n); if (kind == FRACTAL_PAIRING_DEVICE_ENROLLMENT_REQUEST) { m.payload.device.id = m.device_id; m.payload.device.platform = FRACTAL_DEVICE_ANDROID; m.payload.device.attestation = FRACTAL_ATTESTATION_HARDWARE; m.payload.device.key_version = 3u; } if (kind == FRACTAL_PAIRING_DEVICE_PROOF || kind == FRACTAL_PAIRING_SERVICE_PROOF) m.prevalidated_proof = true; if (kind == FRACTAL_PAIRING_HUMAN_VERIFICATION_PENDING) m.payload.approval.code = 424242u; if (kind == FRACTAL_PAIRING_APPROVAL) { m.payload.approval.approved = true; m.payload.approval.role = FRACTAL_ROLE_EDITOR; m.payload.approval.capabilities = fractal_workspace_role_capabilities(FRACTAL_ROLE_EDITOR); m.payload.approval.lifetime_ticks = 30u; } if (kind == FRACTAL_PAIRING_CREDENTIAL_ISSUANCE) { m.payload.credential.capabilities = fractal_workspace_role_capabilities(FRACTAL_ROLE_EDITOR); m.payload.credential.issued_tick = 150u; m.payload.credential.expires_tick = 180u; } return fractal_pairing_reduce(s, &m, 150u); }
static fractal_pairing_state fresh(void) { fractal_pairing_state s; assert(fractal_pairing_state_init(&s, service(), invitation()) == 0); return s; }
static fractal_credential_id happy(fractal_pairing_state *s) { fractal_pairing_transition t; t = step(s, FRACTAL_PAIRING_CLIENT_HELLO, 1u, 10u); assert(t.accepted && t.resulting_stage == FRACTAL_PAIRING_DISCOVERED); t = step(s, FRACTAL_PAIRING_SERVICE_HELLO, 2u, 20u); assert(t.accepted && t.resulting_stage == FRACTAL_PAIRING_INVITATION_PRESENTED); t = step(s, FRACTAL_PAIRING_DEVICE_ENROLLMENT_REQUEST, 3u, 30u); assert(t.accepted); t = step(s, FRACTAL_PAIRING_SERVICE_CHALLENGE, 4u, 40u); assert(t.accepted); t = step(s, FRACTAL_PAIRING_DEVICE_PROOF, 5u, 50u); assert(t.accepted && s->device_proof_verified); t = step(s, FRACTAL_PAIRING_SERVICE_PROOF, 6u, 60u); assert(t.accepted && t.resulting_stage == FRACTAL_PAIRING_KEY_PROOF_VERIFIED); t = step(s, FRACTAL_PAIRING_HUMAN_VERIFICATION_PENDING, 7u, 70u); assert(t.accepted && t.resulting_stage == FRACTAL_PAIRING_HUMAN_CONFIRMATION_REQUIRED); t = step(s, FRACTAL_PAIRING_APPROVAL, 8u, 80u); assert(t.accepted && t.resulting_stage == FRACTAL_PAIRING_APPROVED); t = step(s, FRACTAL_PAIRING_CREDENTIAL_ISSUANCE, 9u, 90u); assert(t.accepted && t.credential_issued && t.resulting_stage == FRACTAL_PAIRING_CREDENTIAL_ISSUED); assert(s->credential_count == 1u && s->invitation.used); t = step(s, FRACTAL_PAIRING_COMPLETE, 10u, 100u); assert(t.accepted && t.resulting_stage == FRACTAL_PAIRING_ACTIVE); return s->credentials[0].id; }
int main(void) { fractal_pairing_state s, s2; fractal_pairing_message m; fractal_pairing_transition t; fractal_pairing_invitation inv = invitation(); assert(!fractal_pairing_id_equal(inv.id, idv(0u))); assert(inv.status == FRACTAL_INVITATION_CREATED && inv.brute_force_limit == 5u);
    s = fresh(); t = step(&s, FRACTAL_PAIRING_CLIENT_HELLO, 1u, 10u); assert(t.accepted); msg(&m, FRACTAL_PAIRING_SERVICE_HELLO, &s, 2u, 20u); t = fractal_pairing_reduce(&s, &m, 201u); assert(!t.accepted && t.rejection == FRACTAL_PAIRING_REJECT_INVITATION);
    s = fresh(); t = step(&s, FRACTAL_PAIRING_SERVICE_HELLO, 1u, 10u); assert(!t.accepted && t.rejection == FRACTAL_PAIRING_REJECT_ORDER);
    s = fresh(); t = step(&s, FRACTAL_PAIRING_CLIENT_HELLO, 1u, 10u); assert(t.accepted); t = step(&s, FRACTAL_PAIRING_SERVICE_HELLO, 2u, 10u); assert(!t.accepted && t.rejection == FRACTAL_PAIRING_REJECT_NONCE_REPLAY);
    s = fresh(); step(&s, FRACTAL_PAIRING_CLIENT_HELLO, 1u, 10u); msg(&m, FRACTAL_PAIRING_SERVICE_HELLO, &s, 2u, 20u); m.previous_transcript = idv(333u); t = fractal_pairing_reduce(&s, &m, 150u); assert(!t.accepted && t.rejection == FRACTAL_PAIRING_REJECT_TRANSCRIPT);
    s = fresh(); step(&s, FRACTAL_PAIRING_CLIENT_HELLO, 1u, 10u); msg(&m, FRACTAL_PAIRING_SERVICE_HELLO, &s, 2u, 20u); m.service_id = idv(11u); t = fractal_pairing_reduce(&s, &m, 150u); assert(!t.accepted && t.rejection == FRACTAL_PAIRING_REJECT_IDENTITY);
    s = fresh(); step(&s, FRACTAL_PAIRING_CLIENT_HELLO, 1u, 10u); step(&s, FRACTAL_PAIRING_SERVICE_HELLO, 2u, 20u); step(&s, FRACTAL_PAIRING_DEVICE_ENROLLMENT_REQUEST, 3u, 30u); step(&s, FRACTAL_PAIRING_SERVICE_CHALLENGE, 4u, 40u); msg(&m, FRACTAL_PAIRING_DEVICE_PROOF, &s, 5u, 50u); m.prevalidated_proof = false; t = fractal_pairing_reduce(&s, &m, 150u); assert(!t.accepted && t.rejection == FRACTAL_PAIRING_REJECT_PROOF);
    s = fresh(); step(&s, FRACTAL_PAIRING_CLIENT_HELLO, 1u, 10u); step(&s, FRACTAL_PAIRING_SERVICE_HELLO, 2u, 20u); step(&s, FRACTAL_PAIRING_DEVICE_ENROLLMENT_REQUEST, 3u, 30u); step(&s, FRACTAL_PAIRING_SERVICE_CHALLENGE, 4u, 40u); step(&s, FRACTAL_PAIRING_DEVICE_PROOF, 5u, 50u); msg(&m, FRACTAL_PAIRING_SERVICE_PROOF, &s, 6u, 60u); m.prevalidated_proof = false; t = fractal_pairing_reduce(&s, &m, 150u); assert(!t.accepted && t.rejection == FRACTAL_PAIRING_REJECT_PROOF);
    s = fresh(); step(&s, FRACTAL_PAIRING_CLIENT_HELLO, 1u, 10u); step(&s, FRACTAL_PAIRING_SERVICE_HELLO, 2u, 20u); step(&s, FRACTAL_PAIRING_DEVICE_ENROLLMENT_REQUEST, 3u, 30u); step(&s, FRACTAL_PAIRING_SERVICE_CHALLENGE, 4u, 40u); step(&s, FRACTAL_PAIRING_DEVICE_PROOF, 5u, 50u); step(&s, FRACTAL_PAIRING_SERVICE_PROOF, 6u, 60u); msg(&m, FRACTAL_PAIRING_HUMAN_VERIFICATION_PENDING, &s, 7u, 70u); m.payload.approval.code = 111111u; t = fractal_pairing_reduce(&s, &m, 150u); assert(!t.accepted && t.rejection == FRACTAL_PAIRING_REJECT_HUMAN_VERIFICATION);
    s = fresh(); step(&s, FRACTAL_PAIRING_CLIENT_HELLO, 1u, 10u); step(&s, FRACTAL_PAIRING_SERVICE_HELLO, 2u, 20u); step(&s, FRACTAL_PAIRING_DEVICE_ENROLLMENT_REQUEST, 3u, 30u); step(&s, FRACTAL_PAIRING_SERVICE_CHALLENGE, 4u, 40u); step(&s, FRACTAL_PAIRING_DEVICE_PROOF, 5u, 50u); step(&s, FRACTAL_PAIRING_SERVICE_PROOF, 6u, 60u); step(&s, FRACTAL_PAIRING_HUMAN_VERIFICATION_PENDING, 7u, 70u); msg(&m, FRACTAL_PAIRING_APPROVAL, &s, 8u, 80u); m.payload.approval.approved = false; t = fractal_pairing_reduce(&s, &m, 150u); assert(!t.accepted && t.rejection == FRACTAL_PAIRING_REJECT_DENIED);
    s = fresh(); step(&s, FRACTAL_PAIRING_CLIENT_HELLO, 1u, 10u); step(&s, FRACTAL_PAIRING_SERVICE_HELLO, 2u, 20u); step(&s, FRACTAL_PAIRING_DEVICE_ENROLLMENT_REQUEST, 3u, 30u); step(&s, FRACTAL_PAIRING_SERVICE_CHALLENGE, 4u, 40u); step(&s, FRACTAL_PAIRING_DEVICE_PROOF, 5u, 50u); step(&s, FRACTAL_PAIRING_SERVICE_PROOF, 6u, 60u); step(&s, FRACTAL_PAIRING_HUMAN_VERIFICATION_PENDING, 7u, 70u); msg(&m, FRACTAL_PAIRING_APPROVAL, &s, 8u, 80u); m.payload.approval.approved = true; m.payload.approval.capabilities = fractal_workspace_role_capabilities(FRACTAL_ROLE_EDITOR) | FRACTAL_CAP_ADMIN; t = fractal_pairing_reduce(&s, &m, 150u); assert(!t.accepted && t.rejection == FRACTAL_PAIRING_REJECT_CAPABILITY);
    s = fresh(); { fractal_credential_id cid = happy(&s); assert(fractal_pairing_revoke_credential(&s, cid, 999u) == 0); assert(s.credentials[0].status == FRACTAL_CREDENTIAL_REVOKED); }
    s = fresh(); s2 = fresh(); happy(&s); happy(&s2); assert(fractal_pairing_id_equal(s.transcript, s2.transcript)); assert(fractal_pairing_id_equal(s.credentials[0].id, s2.credentials[0].id));
    s = fresh(); s.credential_count = FRACTAL_PAIRING_CREDENTIAL_CAPACITY; step(&s, FRACTAL_PAIRING_CLIENT_HELLO, 1u, 10u); step(&s, FRACTAL_PAIRING_SERVICE_HELLO, 2u, 20u); step(&s, FRACTAL_PAIRING_DEVICE_ENROLLMENT_REQUEST, 3u, 30u); step(&s, FRACTAL_PAIRING_SERVICE_CHALLENGE, 4u, 40u); step(&s, FRACTAL_PAIRING_DEVICE_PROOF, 5u, 50u); step(&s, FRACTAL_PAIRING_SERVICE_PROOF, 6u, 60u); step(&s, FRACTAL_PAIRING_HUMAN_VERIFICATION_PENDING, 7u, 70u); step(&s, FRACTAL_PAIRING_APPROVAL, 8u, 80u); t = step(&s, FRACTAL_PAIRING_CREDENTIAL_ISSUANCE, 9u, 90u); assert(!t.accepted && t.rejection == FRACTAL_PAIRING_REJECT_CAPACITY);
    printf("pairing contract tests: ok\n"); return 0; }
