#include "fractal/artifact_sink.h"
#include <stdio.h>
#include <string.h>
#include <limits.h>
static const fractal_module_descriptor memory_descriptor={1,1,"sink.memory.bounded","Bounded memory artifact sink",FRACTAL_MODULE_ARTIFACT_SINK,FRACTAL_CAP_SINK_BINARY_BYTES|FRACTAL_CAP_SINK_COMMIT_ABORT|FRACTAL_CAP_SINK_MEMORY_DESTINATION,true};
static const fractal_module_descriptor file_descriptor={1,1,"sink.file.host","Host file artifact sink",FRACTAL_MODULE_ARTIFACT_SINK,FRACTAL_CAP_SINK_BINARY_BYTES|FRACTAL_CAP_SINK_COMMIT_ABORT|FRACTAL_CAP_SINK_FILE_DESTINATION,true};
static void hash(uint64_t*h,const void*v,size_t n){const unsigned char*p=v;while(n--){*h^=*p++;*h*=UINT64_C(1099511628211);}}
static fractal_result mbegin(void*v,const fractal_artifact_begin_info*i){fractal_memory_sink_state*s=v;if(!s||!i||!i->logical_name||s->phase==1)return FRACTAL_ERROR_INVALID_ARGUMENT;s->used=s->required=0;s->checksum=UINT64_C(1469598103934665603);s->failure=FRACTAL_OK;s->phase=1;return FRACTAL_OK;}
static fractal_result mwrite(void*v,const void*d,size_t n){fractal_memory_sink_state*s=v;if(!s||s->phase!=1||(!d&&n))return FRACTAL_ERROR_INVALID_ARGUMENT;if(n>SIZE_MAX-s->required){s->failure=FRACTAL_ERROR_BUFFER_TOO_SMALL;return s->failure;}s->required+=n;if(n>s->capacity-s->used){s->failure=FRACTAL_ERROR_BUFFER_TOO_SMALL;return s->failure;}memcpy(s->buffer+s->used,d,n);hash(&s->checksum,d,n);s->used+=n;return FRACTAL_OK;}
static fractal_result mcommit(void*v,fractal_artifact_result*r){fractal_memory_sink_state*s=v;if(!s||!r||s->phase!=1)return FRACTAL_ERROR_INVALID_ARGUMENT;if(s->failure!=FRACTAL_OK){r->required_size=s->required;r->result=s->failure;r->committed=false;return s->failure;}s->phase=2;r->sink_module_id=memory_descriptor.module_id;r->destination=FRACTAL_ARTIFACT_DESTINATION_MEMORY;r->byte_count=s->used;r->required_size=s->required;r->encoded_checksum=s->checksum;r->committed=true;r->result=FRACTAL_OK;return FRACTAL_OK;}
static void mabort(void*v){fractal_memory_sink_state*s=v;if(s&&s->phase==1){s->used=0;s->phase=3;}}
void fractal_memory_sink_init(fractal_memory_sink_state*s,void*b,size_t c){if(s){memset(s,0,sizeof(*s));s->buffer=b;s->capacity=c;}}
static int safe_path(const char*p){return p&&*p&&strlen(p)<FRACTAL_ARTIFACT_PATH_CAPACITY-5u&&strstr(p,"..") == NULL&&p[0]!='/';}
fractal_result fractal_file_sink_init(fractal_file_sink_state*s,const char*p){if(!s||!safe_path(p))return FRACTAL_ERROR_INVALID_ARGUMENT;memset(s,0,sizeof(*s));strcpy(s->target,p);if(snprintf(s->temporary,sizeof(s->temporary),"%s.tmp",p)<0)return FRACTAL_ERROR_INVALID_ARGUMENT;return FRACTAL_OK;}
static fractal_result fbegin(void*v,const fractal_artifact_begin_info*i){fractal_file_sink_state*s=v;FILE*f;if(!s||!i||!i->logical_name||s->phase==1||!safe_path(s->target))return FRACTAL_ERROR_INVALID_ARGUMENT;f=fopen(s->temporary,"wb");if(!f)return FRACTAL_ERROR_IO;s->file=f;s->used=0;s->checksum=UINT64_C(1469598103934665603);s->phase=1;s->failure=FRACTAL_OK;return FRACTAL_OK;}
static fractal_result fwrite_sink(void*v,const void*d,size_t n){fractal_file_sink_state*s=v;if(!s||s->phase!=1||(!d&&n))return FRACTAL_ERROR_INVALID_ARGUMENT;if(n>SIZE_MAX-s->used){s->failure=FRACTAL_ERROR_IO;return s->failure;}if(n&&fwrite(d,1,n,(FILE*)s->file)!=n){s->failure=FRACTAL_ERROR_IO;return s->failure;}hash(&s->checksum,d,n);s->used+=n;return FRACTAL_OK;}
static fractal_result fcommit(void*v,fractal_artifact_result*r){fractal_file_sink_state*s=v;FILE*f;if(!s||!r||s->phase!=1)return FRACTAL_ERROR_INVALID_ARGUMENT;f=s->file;s->file=NULL;if(s->failure!=FRACTAL_OK||fflush(f)||fclose(f)||rename(s->temporary,s->target)){remove(s->temporary);s->phase=3;r->committed=false;r->result=FRACTAL_ERROR_IO;return FRACTAL_ERROR_IO;}s->phase=2;r->sink_module_id=file_descriptor.module_id;r->destination=FRACTAL_ARTIFACT_DESTINATION_FILE;r->byte_count=s->used;r->required_size=s->used;r->encoded_checksum=s->checksum;r->committed=true;r->result=FRACTAL_OK;strcpy(r->path,s->target);return FRACTAL_OK;}
static void fabort(void*v){fractal_file_sink_state*s=v;if(s&&s->phase==1){if(s->file)fclose((FILE*)s->file);s->file=NULL;remove(s->temporary);s->phase=3;}}
const fractal_artifact_sink_vtable fractal_artifact_sink_memory={&memory_descriptor,FRACTAL_ARTIFACT_DESTINATION_MEMORY,mbegin,mwrite,mcommit,mabort};
const fractal_artifact_sink_vtable fractal_artifact_sink_host_file={&file_descriptor,FRACTAL_ARTIFACT_DESTINATION_FILE,fbegin,fwrite_sink,fcommit,fabort};
fractal_result fractal_artifact_sink_begin(fractal_artifact_sink*s,const fractal_artifact_begin_info*i){return !s||!s->vtable||!s->vtable->begin?FRACTAL_ERROR_INVALID_ARGUMENT:s->vtable->begin(s->state,i);}
fractal_result fractal_artifact_sink_write(fractal_artifact_sink*s,const void*d,size_t n){return !s||!s->vtable||!s->vtable->write?FRACTAL_ERROR_INVALID_ARGUMENT:s->vtable->write(s->state,d,n);}
fractal_result fractal_artifact_sink_commit(fractal_artifact_sink*s,fractal_artifact_result*r){return !s||!s->vtable||!s->vtable->commit?FRACTAL_ERROR_INVALID_ARGUMENT:s->vtable->commit(s->state,r);}
void fractal_artifact_sink_abort(fractal_artifact_sink*s){if(s&&s->vtable&&s->vtable->abort)s->vtable->abort(s->state);}
