#include "fractal/installed_modules.h"
#include "fractal/artifact_sink.h"
#include <string.h>
#define R(v) {v.descriptor,&v}
fractal_result fractal_installed_modules_registry(fractal_module_registry*r){
 const fractal_module_registration m[]={R(fractal_formula_mandelbrot),R(fractal_formula_julia),R(fractal_numeric_binary64),R(fractal_compute_scalar_v1),R(fractal_compute_conventional),R(fractal_refinement_none),R(fractal_refinement_cdc_unavailable),R(fractal_scheduler_serial),R(fractal_scheduler_serial_v1),R(fractal_scheduler_thread_pool_v1),R(fractal_raster_native),R(fractal_encoder_bmp),R(fractal_memory_system_module),R(fractal_memory_ouro_unavailable_module),R(fractal_telemetry_noop),R(fractal_platform_host),R(fractal_artifact_sink_memory),R(fractal_artifact_sink_host_file),R(fractal_analyzer_passthrough),R(fractal_analyzer_escape_classification_summary),R(fractal_analyzer_iteration_histogram),R(fractal_analyzer_spatial_workload_grid)};
 return fractal_module_registry_init(r,m,sizeof(m)/sizeof(m[0]));
}
static const void*get(const fractal_module_registry*r,fractal_module_kind k,const char*id){const fractal_module_descriptor*d=fractal_module_registry_find(r,k,id);return d&&d->available?fractal_module_registry_implementation(r,k,id):NULL;}
fractal_result fractal_runtime_assemble(const fractal_module_registry*r,const fractal_runtime_selection*s,fractal_memory_backend*m,fractal_runtime_modules*out){const fractal_analyzer_vtable*a[FRACTAL_ANALYZER_CHAIN_MAX]={0};fractal_analysis_request requests[FRACTAL_ANALYZER_CHAIN_MAX];size_t i,count;if(!r||!s||!m||!out||!s->formula||!s->numeric||!s->compute||!s->refinement||!s->scheduler||!s->raster||!s->encoder||!s->memory||!s->telemetry||!s->platform)return FRACTAL_ERROR_INVALID_ARGUMENT;memset(out,0,sizeof(*out));out->formula=get(r,FRACTAL_MODULE_FORMULA,s->formula);out->numeric=get(r,FRACTAL_MODULE_NUMERIC,s->numeric);out->compute=get(r,FRACTAL_MODULE_COMPUTE,s->compute);out->refinement=get(r,FRACTAL_MODULE_REFINEMENT,s->refinement);out->scheduler=get(r,FRACTAL_MODULE_SCHEDULER,s->scheduler);out->raster=get(r,FRACTAL_MODULE_RASTER,s->raster);out->encoder=get(r,FRACTAL_MODULE_ENCODER,s->encoder);out->memory_module=get(r,FRACTAL_MODULE_MEMORY,s->memory);out->telemetry=get(r,FRACTAL_MODULE_TELEMETRY,s->telemetry);out->platform=get(r,FRACTAL_MODULE_PLATFORM,s->platform);out->memory=m;out->scheduler_options.requested_worker_count=s->scheduler_worker_count;if(!out->formula||!out->numeric||!out->compute||!out->refinement||!out->scheduler||!out->raster||!out->encoder||!out->memory_module||!out->telemetry||!out->platform)return FRACTAL_ERROR_NOT_IMPLEMENTED;count=s->analyzer_count;if(!count&&s->analyzer)count=1;if(count>FRACTAL_ANALYZER_CHAIN_MAX)return FRACTAL_ERROR_INVALID_SPEC;for(i=0;i<count;i++){const char*id=s->analyzer_count?s->analyzers[i]:s->analyzer;bool records;if(!id)return FRACTAL_ERROR_INVALID_SPEC;a[i]=get(r,FRACTAL_MODULE_ANALYZER,id);if(!a[i])return FRACTAL_ERROR_NOT_IMPLEMENTED;records=strcmp(id,"fractal.analyzer.passthrough")!=0;requests[i]=(fractal_analysis_request){id,s->analysis_mode,true,records,records?1u:0u};}if(fractal_analysis_pipeline_init_many(&out->analysis,a,requests,count)!=FRACTAL_OK)return FRACTAL_ERROR_INVALID_SPEC;return fractal_runtime_validate(out);}
