#include "fractal/scheduler.h"
#include <stdio.h>
#include <string.h>
#define FNV_OFFSET UINT64_C(1469598103934665603)
#define FNV_PRIME UINT64_C(1099511628211)
static uint64_t hash(uint64_t h,const void*v,size_t n){const unsigned char*p=v;while(n--){h^=*p++;h*=FNV_PRIME;}return h;}
static fractal_result copy(char*d,size_t cap,const char*s){size_t n;if(!s)return FRACTAL_ERROR_INVALID_SPEC;n=strlen(s);if(n>=cap)return FRACTAL_ERROR_INVALID_SPEC;memcpy(d,s,n+1);return FRACTAL_OK;}
fractal_result fractal_work_unit_init(fractal_work_unit*w,const fractal_runtime_modules*r,const fractal_job_spec*j,const fractal_artifact_sink*s,const fractal_cancellation*c){char canonical[1024];int n;if(!w||!r||!j||!s||!s->vtable||fractal_job_spec_validate(r,j)!=FRACTAL_OK||j->problem.parameters.size>FRACTAL_WORK_UNIT_PARAMETER_CAPACITY)return FRACTAL_ERROR_INVALID_SPEC;memset(w,0,sizeof(*w));w->schema_version=1;w->job=*j;if(j->problem.parameters.size){memcpy(w->parameter_storage,j->problem.parameters.data,j->problem.parameters.size);w->job.problem.parameters.data=w->parameter_storage;}if(copy(w->formula_id,sizeof(w->formula_id),r->formula->descriptor->module_id)||copy(w->numeric_id,sizeof(w->numeric_id),r->numeric->descriptor->module_id)||copy(w->compute_id,sizeof(w->compute_id),r->compute->descriptor->module_id)||copy(w->scheduler_id,sizeof(w->scheduler_id),r->scheduler->descriptor->module_id)||copy(w->renderer_id,sizeof(w->renderer_id),r->raster->descriptor->module_id)||copy(w->encoder_id,sizeof(w->encoder_id),r->encoder->descriptor->module_id)||copy(w->sink_id,sizeof(w->sink_id),s->vtable->descriptor->module_id)||copy(w->output_name,sizeof(w->output_name),j->artifact.output_name))return FRACTAL_ERROR_INVALID_SPEC;w->job.problem.formula_id=w->formula_id;w->job.problem.parameters.type_id=w->formula_id;w->job.artifact.encoder_id=w->encoder_id;w->job.artifact.output_name=w->output_name;w->formula_version=r->formula->descriptor->module_version;w->numeric_version=r->numeric->descriptor->module_version;w->compute_version=r->compute->descriptor->module_version;w->scheduler_version=r->scheduler->descriptor->module_version;w->renderer_version=r->raster->descriptor->module_version;w->encoder_version=r->encoder->descriptor->module_version;w->sink_version=s->vtable->descriptor->module_version;w->analysis_chain_identity=r->analysis.identity;w->cancellation=c;n=snprintf(canonical,sizeof(canonical),"v1|%s@%u|%s@%u|%s@%u|%s@%u|%s@%u|%s@%u|%s@%u|%016llx|%.17g|%.17g|%.17g|%u|%u|%u|%s",w->formula_id,w->formula_version,w->numeric_id,w->numeric_version,w->compute_id,w->compute_version,w->scheduler_id,w->scheduler_version,w->renderer_id,w->renderer_version,w->encoder_id,w->encoder_version,w->sink_id,w->sink_version,(unsigned long long)w->analysis_chain_identity,j->view.center_real,j->view.center_imaginary,j->view.scale,j->view.width,j->view.height,j->problem.maximum_steps,w->output_name);if(n<0||(size_t)n>=sizeof(canonical))return FRACTAL_ERROR_INVALID_SPEC;w->identity=hash(FNV_OFFSET,canonical,(size_t)n);w->identity=hash(w->identity,w->parameter_storage,j->problem.parameters.size);w->sealed=true;return FRACTAL_OK;}
fractal_result fractal_work_unit_validate(const fractal_work_unit*w,const fractal_runtime_modules*r,const fractal_artifact_sink*s){if(!w||!w->sealed||w->schema_version!=1||!w->identity||!r||!s||!s->vtable)return FRACTAL_ERROR_INVALID_SPEC;if(strcmp(w->scheduler_id,r->scheduler->descriptor->module_id)||w->scheduler_version!=r->scheduler->descriptor->module_version||strcmp(w->compute_id,r->compute->descriptor->module_id)||strcmp(w->renderer_id,r->raster->descriptor->module_id)||strcmp(w->sink_id,s->vtable->descriptor->module_id)||w->analysis_chain_identity!=r->analysis.identity)return FRACTAL_ERROR_INVALID_SPEC;return fractal_job_spec_validate(r,&w->job);}
const char*fractal_scheduler_status_string(fractal_scheduler_status s){static const char*n[]={"not_started","rejected","cancelled","compute_failed","analysis_failed","renderer_failed","sink_failed","published"};return (unsigned)s<sizeof(n)/sizeof(n[0])?n[s]:"invalid";}
/* The full lifecycle remains routed through runtime_render_artifact while that API owns allocations. This socket establishes one authoritative, serial publication boundary. */
fractal_result fractal_scheduler_execute_artifact(const fractal_runtime_modules*r,const fractal_work_unit*w,fractal_artifact_sink*s,fractal_runtime_output*o,fractal_artifact_result*a,fractal_scheduler_execution*e){fractal_result q;if(!e)return FRACTAL_ERROR_INVALID_ARGUMENT;memset(e,0,sizeof(*e));e->work_unit_identity=w?w->identity:0;e->last_phase=FRACTAL_SCHEDULER_PHASE_PREPARE;e->sequence_begin=1;if(w&&w->cancellation&&w->cancellation->requested){e->status=FRACTAL_SCHEDULER_CANCELLED;e->result=FRACTAL_ERROR_CANCELLED;e->sequence_end=2;return e->result;}e->last_phase=FRACTAL_SCHEDULER_PHASE_VALIDATE;if(fractal_work_unit_validate(w,r,s)!=FRACTAL_OK){e->status=FRACTAL_SCHEDULER_REJECTED;e->result=FRACTAL_ERROR_INVALID_SPEC;e->sequence_end=2;return e->result;}e->last_phase=FRACTAL_SCHEDULER_PHASE_COMPUTE;q=fractal_runtime_render_artifact(r,&w->job,s,w->cancellation,o,a);if(q!=FRACTAL_OK){e->status=q==FRACTAL_ERROR_CANCELLED?FRACTAL_SCHEDULER_CANCELLED:(a&&a->result!=FRACTAL_OK?FRACTAL_SCHEDULER_SINK_FAILED:FRACTAL_SCHEDULER_COMPUTE_FAILED);e->result=q;e->sequence_end=3;return q;}o->work_unit_identity=w->identity;o->scheduler_status=FRACTAL_SCHEDULER_PUBLISHED;e->last_phase=FRACTAL_SCHEDULER_PHASE_PUBLISH;e->status=FRACTAL_SCHEDULER_PUBLISHED;e->result=FRACTAL_OK;e->published=true;e->sequence_end=7;return FRACTAL_OK;}
