#include "fractal/socketable_runtime.h"
#include <math.h>
#include <stdio.h>
#include <string.h>

#define DESC(name,id,title,kind,caps) static const fractal_module_descriptor name={1u,1u,id,title,kind,caps}
DESC(d_num,"numeric.binary64","IEEE-754 binary64",FRACTAL_MODULE_NUMERIC,FRACTAL_CAP_SCALAR_ARITHMETIC);
DESC(d_man,"formula.mandelbrot.quadratic","Mandelbrot quadratic",FRACTAL_MODULE_FORMULA,FRACTAL_CAP_POINT_SCALAR);
DESC(d_jul,"formula.julia.quadratic","Julia quadratic",FRACTAL_MODULE_FORMULA,FRACTAL_CAP_POINT_SCALAR);
DESC(d_compute,"compute.conventional.scalar-c","Conventional scalar C",FRACTAL_MODULE_COMPUTE,FRACTAL_CAP_POINT_SCALAR);
DESC(d_none,"refinement.none","No refinement",FRACTAL_MODULE_REFINEMENT,0);
DESC(d_cdc,"refinement.cdc.unavailable","CDC refinement (unavailable)",FRACTAL_MODULE_REFINEMENT,0);
DESC(d_sched,"scheduler.serial.row-major","Serial row-major",FRACTAL_MODULE_SCHEDULER,FRACTAL_CAP_SERIAL_FIELD|FRACTAL_CAP_ITERATION_FIELD);
DESC(d_raster,"raster.native.iteration-bgr8","Native iteration rasterizer",FRACTAL_MODULE_RASTER,FRACTAL_CAP_ITERATION_FIELD|FRACTAL_CAP_BGR8);
DESC(d_bmp,"encoder.bmp.v3","BMP v3 encoder",FRACTAL_MODULE_ENCODER,FRACTAL_CAP_BGR8);
DESC(d_mem,"memory.system.scoped","System scoped memory",FRACTAL_MODULE_MEMORY,FRACTAL_CAP_MEMORY_SCOPES);
DESC(d_ouro,"memory.ouro.unavailable","Ouro memory (unavailable)",FRACTAL_MODULE_MEMORY,0);
DESC(d_tel,"telemetry.noop","No-op telemetry",FRACTAL_MODULE_TELEMETRY,0);
DESC(d_host,"platform.host.c11","Host C11 platform",FRACTAL_MODULE_PLATFORM,0);

static double get(const fractal_scalar *s){double v;memcpy(&v,s->storage,8);return v;} static void put(fractal_scalar*s,double v){memcpy(s->storage,&v,8);}
static fractal_result from(double v,fractal_scalar*s){if(!s||!isfinite(v))return FRACTAL_ERROR_INVALID_ARGUMENT;put(s,v);return FRACTAL_OK;}
static fractal_result to(const fractal_scalar*s,double*v){if(!s||!v)return FRACTAL_ERROR_INVALID_ARGUMENT;*v=get(s);return FRACTAL_OK;}
#define OP(fn,expr) static fractal_result fn(const fractal_scalar*a,const fractal_scalar*b,fractal_scalar*o){double v;if(!a||!b||!o)return FRACTAL_ERROR_INVALID_ARGUMENT;v=(expr);if(!isfinite(v))return FRACTAL_ERROR_INVALID_SPEC;put(o,v);return FRACTAL_OK;}
OP(add,get(a)+get(b)) OP(sub,get(a)-get(b)) OP(mul,get(a)*get(b))
static bool finite_scalar(const fractal_scalar*s){return s&&isfinite(get(s));}
static fractal_result serialize_scalar(const fractal_scalar*s,char*b,size_t c,size_t*l){uint64_t bits;int n;if(!s||!l)return FRACTAL_ERROR_INVALID_ARGUMENT;memcpy(&bits,s->storage,8);n=snprintf(b,c,"%016llx",(unsigned long long)bits);*l=16u;return n<0||!b||c<17u?FRACTAL_ERROR_BUFFER_TOO_SMALL:FRACTAL_OK;}
const fractal_numeric_vtable fractal_numeric_binary64={&d_num,53u,8u,8u,from,to,add,sub,mul,finite_scalar,serialize_scalar};

static fractal_result valid_params(const fractal_formula_parameters*p,const char*id,size_t size){if(!p||!p->type_id||strcmp(p->type_id,id)||!p->data||p->size!=size)return FRACTAL_ERROR_INVALID_SPEC;return FRACTAL_OK;}
static fractal_result valid_man(const fractal_formula_parameters*p){const fractal_mandelbrot_parameters*q;if(valid_params(p,d_man.module_id,sizeof(*q))!=FRACTAL_OK)return FRACTAL_ERROR_INVALID_SPEC;q=p->data;return isfinite(q->escape_radius)&&q->escape_radius>0.0?FRACTAL_OK:FRACTAL_ERROR_INVALID_SPEC;}
static fractal_result valid_jul(const fractal_formula_parameters*p){const fractal_julia_parameters*q;if(valid_params(p,d_jul.module_id,sizeof(*q))!=FRACTAL_OK)return FRACTAL_ERROR_INVALID_SPEC;q=p->data;return isfinite(q->constant_real)&&isfinite(q->constant_imaginary)&&isfinite(q->escape_radius)&&q->escape_radius>0.0?FRACTAL_OK:FRACTAL_ERROR_INVALID_SPEC;}
static size_t state_size(void){return sizeof(fractal_complex_state);} static size_t state_align(void){return _Alignof(fractal_complex_state);}
static fractal_result init_common(const fractal_numeric_vtable*n,double zr,double zi,double cr,double ci,double radius,void*out){fractal_complex_state*s=out;fractal_scalar r;if(!n||!out)return FRACTAL_ERROR_INVALID_ARGUMENT;if(n->from_double(zr,&s->zr)||n->from_double(zi,&s->zi)||n->from_double(cr,&s->cr)||n->from_double(ci,&s->ci)||n->from_double(radius,&r)||n->multiply(&r,&r,&s->radius_squared))return FRACTAL_ERROR_INVALID_SPEC;return FRACTAL_OK;}
static fractal_result init_man(const fractal_numeric_vtable*n,const fractal_formula_parameters*p,double x,double y,void*s){const fractal_mandelbrot_parameters*q;if(valid_man(p)!=FRACTAL_OK)return FRACTAL_ERROR_INVALID_SPEC;q=p->data;return init_common(n,0,0,x,y,q->escape_radius,s);}
static fractal_result init_jul(const fractal_numeric_vtable*n,const fractal_formula_parameters*p,double x,double y,void*s){const fractal_julia_parameters*q;if(valid_jul(p)!=FRACTAL_OK)return FRACTAL_ERROR_INVALID_SPEC;q=p->data;return init_common(n,x,y,q->constant_real,q->constant_imaginary,q->escape_radius,s);}
static fractal_result step(const fractal_numeric_vtable*n,void*v){fractal_complex_state*s=v;fractal_scalar rr,ii,ri,two,next_r,next_i;if(!n||!s)return FRACTAL_ERROR_INVALID_ARGUMENT;if(n->multiply(&s->zr,&s->zr,&rr)||n->multiply(&s->zi,&s->zi,&ii)||n->subtract(&rr,&ii,&next_r)||n->add(&next_r,&s->cr,&next_r)||n->multiply(&s->zr,&s->zi,&ri)||n->from_double(2,&two)||n->multiply(&two,&ri,&next_i)||n->add(&next_i,&s->ci,&next_i))return FRACTAL_ERROR_INVALID_SPEC;s->zr=next_r;s->zi=next_i;return FRACTAL_OK;}
static fractal_result classify(const fractal_numeric_vtable*n,const void*v,fractal_point_class*c){const fractal_complex_state*s=v;fractal_scalar rr,ii,m;if(!n||!s||!c)return FRACTAL_ERROR_INVALID_ARGUMENT;if(n->multiply(&s->zr,&s->zr,&rr)||n->multiply(&s->zi,&s->zi,&ii)||n->add(&rr,&ii,&m)){*c=FRACTAL_CLASS_FAILED;return FRACTAL_OK;}*c=get(&m)>get(&s->radius_squared)?FRACTAL_CLASS_ESCAPED:FRACTAL_CLASS_UNRESOLVED;return FRACTAL_OK;}
static fractal_result ser_man(const fractal_formula_parameters*p,char*b,size_t c,size_t*l){const fractal_mandelbrot_parameters*q;int n;if(valid_man(p)!=FRACTAL_OK||!l)return FRACTAL_ERROR_INVALID_SPEC;q=p->data;n=snprintf(b,c,"{\"escape_radius\":%.17g}",q->escape_radius);*l=n<0?0u:(size_t)n;return n<0||!b||c<=(size_t)n?FRACTAL_ERROR_BUFFER_TOO_SMALL:FRACTAL_OK;}
static fractal_result ser_jul(const fractal_formula_parameters*p,char*b,size_t c,size_t*l){const fractal_julia_parameters*q;int n;if(valid_jul(p)!=FRACTAL_OK||!l)return FRACTAL_ERROR_INVALID_SPEC;q=p->data;n=snprintf(b,c,"{\"constant_imaginary\":%.17g,\"constant_real\":%.17g,\"escape_radius\":%.17g}",q->constant_imaginary,q->constant_real,q->escape_radius);*l=n<0?0u:(size_t)n;return n<0||!b||c<=(size_t)n?FRACTAL_ERROR_BUFFER_TOO_SMALL:FRACTAL_OK;}
const fractal_formula_vtable fractal_formula_mandelbrot={&d_man,FRACTAL_CAP_SCALAR_ARITHMETIC,valid_man,state_size,state_align,init_man,step,classify,ser_man};
const fractal_formula_vtable fractal_formula_julia={&d_jul,FRACTAL_CAP_SCALAR_ARITHMETIC,valid_jul,state_size,state_align,init_jul,step,classify,ser_jul};

static fractal_result point(const fractal_formula_vtable*f,const fractal_numeric_vtable*n,const fractal_formula_parameters*p,double x,double y,uint32_t budget,const fractal_cancellation*cancel,fractal_point_result_compact*out){fractal_complex_state state;uint32_t i;if(!f||!n||!out||budget==0||f->state_size()>sizeof(state)||f->validate_parameters(p)!=FRACTAL_OK)return FRACTAL_ERROR_INVALID_ARGUMENT;memset(out,0,sizeof(*out));out->classification=FRACTAL_CLASS_UNRESOLVED;if(f->initialize_state(n,p,x,y,&state)!=FRACTAL_OK)return FRACTAL_ERROR_INVALID_SPEC;for(i=1;i<=budget;i++){fractal_point_class c;if(cancel&&cancel->requested){out->classification=FRACTAL_CLASS_CANCELLED;return FRACTAL_ERROR_CANCELLED;}if(f->step(n,&state)!=FRACTAL_OK){out->classification=FRACTAL_CLASS_FAILED;return FRACTAL_OK;}out->steps=i;if(f->classify(n,&state,&c)!=FRACTAL_OK)return FRACTAL_ERROR_INVALID_SPEC;if(c==FRACTAL_CLASS_ESCAPED){out->classification=(uint8_t)c;return FRACTAL_OK;}}return FRACTAL_OK;}
const fractal_compute_vtable fractal_compute_conventional={&d_compute,FRACTAL_CAP_POINT_SCALAR,FRACTAL_CAP_SCALAR_ARITHMETIC,point};
const fractal_refinement_vtable fractal_refinement_none={&d_none,true},fractal_refinement_cdc_unavailable={&d_cdc,false};

static fractal_result execute(const fractal_runtime_modules*r,const fractal_job_spec*j,fractal_field*f,const fractal_cancellation*c,fractal_progress_fn progress,void*ctx){uint32_t y,x;double aspect;if(!r||!j||!f||!f->samples)return FRACTAL_ERROR_INVALID_ARGUMENT;aspect=(double)j->view.width/(double)j->view.height;for(y=0;y<j->view.height;y++){for(x=0;x<j->view.width;x++){double re=j->view.center_real+(((double)x+0.5)/(double)j->view.width-0.5)*j->view.scale*aspect;double im=j->view.center_imaginary+(0.5-((double)y+0.5)/(double)j->view.height)*j->view.scale;fractal_result q=r->compute->point(r->formula,r->numeric,&j->problem.parameters,re,im,j->problem.maximum_steps,c,&f->samples[(size_t)y*j->view.width+x]);if(q!=FRACTAL_OK)return q;}f->completed_rows=y+1;if(progress)progress(y+1,j->view.height,ctx);}f->complete=true;return FRACTAL_OK;}
const fractal_scheduler_vtable fractal_scheduler_serial={&d_sched,FRACTAL_CAP_POINT_SCALAR,FRACTAL_CAP_ITERATION_FIELD,execute};
static fractal_result rasterize(const fractal_field*f,uint32_t max,fractal_pixel_buffer*p){uint32_t y,x;if(!f||!p||!p->pixels||!f->complete||!max)return FRACTAL_ERROR_INVALID_ARGUMENT;for(y=0;y<f->height;y++)for(x=0;x<f->width;x++){const fractal_point_result_compact*s=&f->samples[(size_t)y*f->width+x];unsigned char*v=&p->pixels[(size_t)y*p->stride+(size_t)x*3u];if(s->classification==FRACTAL_CLASS_ESCAPED){v[0]=(unsigned char)((s->steps*29u)&255u);v[1]=(unsigned char)((s->steps*13u)&255u);v[2]=(unsigned char)(255u-(s->steps*7u&255u));}else v[0]=v[1]=v[2]=0; }return FRACTAL_OK;}
const fractal_raster_vtable fractal_raster_native={&d_raster,FRACTAL_CAP_ITERATION_FIELD,FRACTAL_CAP_BGR8,rasterize};
static void le32(unsigned char*b,uint32_t v){b[0]=(unsigned char)v;b[1]=(unsigned char)(v>>8);b[2]=(unsigned char)(v>>16);b[3]=(unsigned char)(v>>24);} static void le16(unsigned char*b,uint16_t v){b[0]=(unsigned char)v;b[1]=(unsigned char)(v>>8);}
static fractal_result encode(const fractal_pixel_buffer*p,fractal_write_sink*s){unsigned char h[54]={0},pad[3]={0};uint32_t y,row,file;if(!p||!s||!s->write||p->format!=FRACTAL_PIXEL_BGR8)return FRACTAL_ERROR_INVALID_ARGUMENT;row=(p->width*3u+3u)&~3u;file=54u+row*p->height;h[0]='B';h[1]='M';le32(h+2,file);le32(h+10,54);le32(h+14,40);le32(h+18,p->width);le32(h+22,p->height);le16(h+26,1);le16(h+28,24);le32(h+34,row*p->height);if(s->write(s->context,h,54)!=FRACTAL_OK)return FRACTAL_ERROR_IO;for(y=p->height;y>0;y--){if(s->write(s->context,p->pixels+(size_t)(y-1)*p->stride,p->width*3u)!=FRACTAL_OK||(row>p->width*3u&&s->write(s->context,pad,row-p->width*3u)!=FRACTAL_OK))return FRACTAL_ERROR_IO;}return FRACTAL_OK;}
const fractal_encoder_vtable fractal_encoder_bmp={&d_bmp,FRACTAL_CAP_BGR8,encode};
const fractal_memory_vtable fractal_memory_system_module={&d_mem},fractal_memory_ouro_unavailable_module={&d_ouro};
static void noop(void*s,const fractal_telemetry_event*e){(void)s;(void)e;} const fractal_telemetry_vtable fractal_telemetry_noop={&d_tel,noop}; const fractal_platform_vtable fractal_platform_host={&d_host};

fractal_result fractal_runtime_validate(const fractal_runtime_modules*r){const fractal_module_descriptor*d[10];if(!r||!r->formula||!r->numeric||!r->compute||!r->refinement||!r->scheduler||!r->raster||!r->encoder||!r->memory_module||!r->memory||!r->telemetry||!r->platform)return FRACTAL_ERROR_INVALID_ARGUMENT;d[0]=r->formula->descriptor;d[1]=r->numeric->descriptor;d[2]=r->compute->descriptor;d[3]=r->refinement->descriptor;d[4]=r->scheduler->descriptor;d[5]=r->raster->descriptor;d[6]=r->encoder->descriptor;d[7]=r->memory_module->descriptor;d[8]=r->telemetry->descriptor;d[9]=r->platform->descriptor;for(unsigned i=0;i<10;i++)if(fractal_module_descriptor_validate(d[i],(fractal_module_kind)i)!=FRACTAL_OK)return FRACTAL_ERROR_INVALID_SPEC;if(!r->refinement->available||r->memory_module==&fractal_memory_ouro_unavailable_module||r->memory->kind!=FRACTAL_MEMORY_BACKEND_SYSTEM)return FRACTAL_ERROR_NOT_IMPLEMENTED;if((r->numeric->descriptor->capability_flags&r->formula->required_numeric_capabilities)!=r->formula->required_numeric_capabilities||(r->formula->descriptor->capability_flags&r->compute->required_formula_capabilities)!=r->compute->required_formula_capabilities||(r->numeric->descriptor->capability_flags&r->compute->required_numeric_capabilities)!=r->compute->required_numeric_capabilities||(r->scheduler->produced_capabilities&r->raster->accepted_field_capabilities)!=r->raster->accepted_field_capabilities||(r->raster->produced_capabilities&r->encoder->accepted_pixel_capabilities)!=r->encoder->accepted_pixel_capabilities)return FRACTAL_ERROR_INVALID_SPEC;return FRACTAL_OK;}
fractal_result fractal_job_spec_validate(const fractal_runtime_modules*r,const fractal_job_spec*j){if(fractal_runtime_validate(r)!=FRACTAL_OK||!j||!j->problem.formula_id||strcmp(j->problem.formula_id,r->formula->descriptor->module_id)||!j->artifact.encoder_id||strcmp(j->artifact.encoder_id,r->encoder->descriptor->module_id)||!j->raster.palette_id||strcmp(j->raster.palette_id,"palette.socket-v1")||j->raster.pixel_format!=FRACTAL_PIXEL_BGR8||!j->view.width||!j->view.height||j->view.width>4096||j->view.height>4096||!isfinite(j->view.scale)||j->view.scale<=0||!j->problem.maximum_steps)return FRACTAL_ERROR_INVALID_SPEC;return r->formula->validate_parameters(&j->problem.parameters);}
uint64_t fractal_checksum64(const void*d,size_t n){const unsigned char*p=d;uint64_t h=UINT64_C(1469598103934665603);while(n--){h^=*p++;h*=UINT64_C(1099511628211);}return h;}
typedef struct counting_sink {fractal_write_sink *next;uint64_t hash;size_t bytes;} counting_sink;static fractal_result count_write(void*c,const void*d,size_t n){counting_sink*x=c;const unsigned char*p=d;x->bytes+=n;while(n--){x->hash^=*p++;x->hash*=UINT64_C(1099511628211);}return x->next->write(x->next->context,d,(size_t)(p-(const unsigned char*)d));}
fractal_result fractal_runtime_render(const fractal_runtime_modules*r,const fractal_job_spec*j,fractal_write_sink*s,const fractal_cancellation*c,fractal_runtime_output*o){fractal_memory_scope scope;counting_sink cs;fractal_write_sink wrapped;fractal_result q;if(!o||!s||fractal_job_spec_validate(r,j)!=FRACTAL_OK)return FRACTAL_ERROR_INVALID_SPEC;memset(o,0,sizeof(*o));if(fractal_memory_scope_begin(r->memory,FRACTAL_MEMORY_SCOPE_SHORT,&scope)!=FRACTAL_OK)return FRACTAL_ERROR_OUT_OF_MEMORY;o->field.width=j->view.width;o->field.height=j->view.height;o->field.stride=(size_t)j->view.width*sizeof(*o->field.samples);o->field.samples=fractal_memory_scope_alloc(&scope,o->field.stride*j->view.height,_Alignof(fractal_point_result_compact));o->pixels.width=j->view.width;o->pixels.height=j->view.height;o->pixels.stride=(size_t)j->view.width*3u;o->pixels.format=FRACTAL_PIXEL_BGR8;o->pixels.pixels=fractal_memory_scope_alloc(&scope,o->pixels.stride*j->view.height,1u);if(!o->field.samples||!o->pixels.pixels){fractal_memory_scope_end(&scope);return FRACTAL_ERROR_OUT_OF_MEMORY;}q=r->scheduler->execute(r,j,&o->field,c,NULL,NULL);if(q==FRACTAL_OK)q=r->raster->rasterize(&o->field,j->problem.maximum_steps,&o->pixels);o->field_checksum=fractal_checksum64(o->field.samples,o->field.stride*o->field.height);o->pixel_checksum=fractal_checksum64(o->pixels.pixels,o->pixels.stride*o->pixels.height);cs=(counting_sink){s,UINT64_C(1469598103934665603),0};wrapped=(fractal_write_sink){&cs,count_write};if(q==FRACTAL_OK)q=r->encoder->encode(&o->pixels,&wrapped);o->artifact_checksum=cs.hash;o->artifact_bytes=cs.bytes;/* output pointers are intentionally invalid after this call; checksums are the durable result */fractal_memory_scope_end(&scope);o->field.samples=NULL;o->pixels.pixels=NULL;return q;}
fractal_result fractal_runtime_manifest(const fractal_runtime_modules*r,const fractal_job_spec*j,const fractal_runtime_output*o,char*b,size_t c,size_t*l){char params[192];size_t pl;int n;if(!l||!o||fractal_job_spec_validate(r,j)!=FRACTAL_OK||r->formula->serialize_parameters(&j->problem.parameters,params,sizeof(params),&pl)!=FRACTAL_OK)return FRACTAL_ERROR_INVALID_SPEC;n=snprintf(b,c,"{\"abi\":1,\"application_revision\":\"socketable-runtime-v1\",\"artifact_checksum\":\"%016llx\",\"compute\":\"%s@1\",\"encoder\":\"%s@1\",\"field_checksum\":\"%016llx\",\"formula\":\"%s@1\",\"formula_parameters\":%s,\"memory\":\"%s@1\",\"numeric\":\"%s@1/53-bit\",\"pixel_checksum\":\"%016llx\",\"pixel_format\":\"BGR8\",\"platform\":\"%s@1\",\"raster\":\"%s@1\",\"refinement\":\"%s@1\",\"scheduler\":\"%s@1\",\"telemetry\":\"%s@1\",\"traversal\":\"row-major\"}",(unsigned long long)o->artifact_checksum,r->compute->descriptor->module_id,r->encoder->descriptor->module_id,(unsigned long long)o->field_checksum,r->formula->descriptor->module_id,params,r->memory_module->descriptor->module_id,r->numeric->descriptor->module_id,(unsigned long long)o->pixel_checksum,r->platform->descriptor->module_id,r->raster->descriptor->module_id,r->refinement->descriptor->module_id,r->scheduler->descriptor->module_id,r->telemetry->descriptor->module_id);*l=n<0?0u:(size_t)n;return n<0||!b||c<=(size_t)n?FRACTAL_ERROR_BUFFER_TOO_SMALL:FRACTAL_OK;}
