#ifndef FRACTAL_WORKSPACE_CONTROLLER_H
#define FRACTAL_WORKSPACE_CONTROLLER_H
#include "fractal/desktop_client_core.h"
#ifdef __cplusplus
extern "C" {
#endif
#define FRACTAL_RENDER_CONFIGURATION_VERSION 1u
#define FRACTAL_RENDER_CONFIGURATION_MAX_ANALYZERS 8u
#define FRACTAL_RENDER_CONFIGURATION_MAX_BYTES 2048u
typedef enum fractal_controller_state{FRACTAL_CONTROLLER_DISCONNECTED=0,FRACTAL_CONTROLLER_CONNECTING,FRACTAL_CONTROLLER_SYNCHRONIZING,FRACTAL_CONTROLLER_READY,FRACTAL_CONTROLLER_EDITING,FRACTAL_CONTROLLER_SUBMITTING,FRACTAL_CONTROLLER_RENDERING,FRACTAL_CONTROLLER_ANALYZING,FRACTAL_CONTROLLER_PUBLISHING,FRACTAL_CONTROLLER_COMPLETE,FRACTAL_CONTROLLER_CANCELLING,FRACTAL_CONTROLLER_FAILED}fractal_controller_state;
typedef enum fractal_runtime_stage{FRACTAL_RUNTIME_IDLE=0,FRACTAL_RUNTIME_QUEUED,FRACTAL_RUNTIME_PREPARING,FRACTAL_RUNTIME_RENDERING,FRACTAL_RUNTIME_ANALYSIS_PENDING,FRACTAL_RUNTIME_ANALYZING,FRACTAL_RUNTIME_PUBLISHING,FRACTAL_RUNTIME_COMPLETED,FRACTAL_RUNTIME_CANCELLING,FRACTAL_RUNTIME_CANCELLED,FRACTAL_RUNTIME_FAILED,FRACTAL_RUNTIME_SUPERSEDED}fractal_runtime_stage;
typedef enum fractal_analysis_policy{FRACTAL_ANALYSIS_OFF=0,FRACTAL_ANALYSIS_CHECKPOINT,FRACTAL_ANALYSIS_DEFERRED}fractal_analysis_policy;
typedef enum fractal_analysis_state{FRACTAL_ANALYSIS_NOT_REQUESTED=0,FRACTAL_ANALYSIS_PENDING,FRACTAL_ANALYSIS_WAITING_FOR_IDLE,FRACTAL_ANALYSIS_RUNNING,FRACTAL_ANALYSIS_COMPLETED,FRACTAL_ANALYSIS_CANCELLED,FRACTAL_ANALYSIS_SUPERSEDED,FRACTAL_ANALYSIS_FAILED}fractal_analysis_state;
typedef struct fractal_render_configuration{uint32_t version;fractal_render_spec render_spec;char formula_id[FRACTAL_IDENTIFIER_CAPACITY];double formula_parameters[FRACTAL_WORKSPACE_PARAMETER_CAPACITY];uint32_t formula_parameter_count;char numeric_id[FRACTAL_IDENTIFIER_CAPACITY];uint64_t iteration_budget;double bailout;char scheduler_id[FRACTAL_IDENTIFIER_CAPACITY];char analyzer_ids[FRACTAL_RENDER_CONFIGURATION_MAX_ANALYZERS][FRACTAL_IDENTIFIER_CAPACITY];uint32_t analyzer_count;uint32_t palette_id;uint32_t output_policy;uint64_t identity;uint64_t checksum;}fractal_render_configuration;
typedef struct fractal_runtime_progress_snapshot{fractal_workspace_id workspace_id;uint64_t generation;fractal_runtime_stage stage;uint64_t completed_work_units;uint64_t total_work_units;uint64_t rows_completed;uint64_t elapsed_ticks;bool cancellation_requested;uint64_t latest_preview_sequence;fractal_analysis_state analyzer_status;bool artifact_published;uint32_t error_status;uint64_t progress_identity;}fractal_runtime_progress_snapshot;
typedef struct fractal_preview_snapshot{fractal_workspace_id workspace_id;uint64_t generation;uint64_t preview_sequence;uint32_t completeness_basis_points;uint32_t width;uint32_t height;uint64_t preview_identity;uint64_t source_field_revision;bool stale_or_superseded;}fractal_preview_snapshot;
typedef struct fractal_analysis_checkpoint_record{fractal_workspace_id workspace_id;uint64_t generation;uint64_t field_identity;uint64_t analyzer_chain_identity;fractal_analysis_policy policy;fractal_analysis_state state;uint64_t scheduling_revision;uint64_t idle_ticks_observed;uint64_t started_ticks;uint64_t completed_ticks;uint64_t result_identity;uint64_t artifact_identity;uint32_t cancellation_reason;uint64_t checkpoint_identity;}fractal_analysis_checkpoint_record;
typedef struct fractal_analysis_cost_observation{uint64_t jobs_requested;uint64_t jobs_skipped;uint64_t jobs_cancelled_by_supersession;uint64_t jobs_completed;uint64_t analyzer_elapsed_ticks;uint64_t render_elapsed_ticks;uint32_t analysis_to_render_ratio_basis_points;uint32_t selected_analyzer_count;}fractal_analysis_cost_observation;
typedef struct fractal_workspace_controller{fractal_controller_state state;fractal_local_service service;fractal_participant_id participant;uint64_t next_command_sequence;fractal_runtime_progress_snapshot progress;fractal_preview_snapshot preview;fractal_analysis_checkpoint_record analysis;fractal_analysis_cost_observation cost;fractal_render_configuration configuration;uint64_t artifact_identity;uint32_t semantic_drift;}fractal_workspace_controller;
typedef struct fractal_controller_summary{fractal_controller_state controller_state;uint64_t workspace_revision;uint64_t generation;fractal_runtime_stage runtime_stage;uint64_t completed_work_units;uint64_t total_work_units;uint64_t preview_identity;fractal_analysis_state analysis_state;uint64_t analysis_identity;uint64_t artifact_identity;uint32_t semantic_drift;uint32_t error_status;}fractal_controller_summary;
const char*fractal_controller_state_name(fractal_controller_state state);
const char*fractal_runtime_stage_name(fractal_runtime_stage stage);
const char*fractal_analysis_policy_name(fractal_analysis_policy policy);
const char*fractal_analysis_state_name(fractal_analysis_state state);
int fractal_render_configuration_default(fractal_render_configuration*config);
int fractal_render_configuration_validate(const fractal_render_configuration*config);
int fractal_render_configuration_save_local(const fractal_render_configuration*config,const char*directory,char*out_name,size_t out_capacity);
int fractal_render_configuration_load_local(fractal_render_configuration*config,const char*directory,uint64_t identity);
int fractal_workspace_controller_init(fractal_workspace_controller*controller,fractal_analysis_policy policy);
int fractal_workspace_controller_apply_configuration(fractal_workspace_controller*controller,const fractal_render_configuration*config);
int fractal_workspace_controller_start(fractal_workspace_controller*controller);
int fractal_workspace_controller_wait(fractal_workspace_controller*controller,uint32_t ticks);
int fractal_workspace_controller_cancel(fractal_workspace_controller*controller);
int fractal_workspace_controller_rapid_edit(fractal_workspace_controller*controller,uint32_t edits);
fractal_controller_summary fractal_workspace_controller_summary(const fractal_workspace_controller*controller);
int fractal_workspace_controller_run_reference(fractal_analysis_policy policy,fractal_controller_summary*out);
#ifdef __cplusplus
}
#endif
#endif
