#include "fractal/analysis.h"
#include "fractal/socketable_runtime.h"
#include <inttypes.h>
#include <stdio.h>
#include <string.h>

#define FNV_OFFSET UINT64_C(1469598103934665603)
#define FNV_PRIME UINT64_C(1099511628211)
#define SUMMARY_PAYLOAD_SIZE 97u
#define HISTOGRAM_PAYLOAD_SIZE 569u

static uint64_t hash_bytes(const void *data,size_t n){const unsigned char*p=data;uint64_t h=FNV_OFFSET;while(n--){h^=*p++;h*=FNV_PRIME;}return h;}
static bool add_u64(uint64_t *v,uint64_t n){if(*v>UINT64_MAX-n)return false;*v+=n;return true;}
static void put_u64(unsigned char *p,uint64_t v){unsigned i;for(i=0;i<8;i++)p[i]=(unsigned char)(v>>(i*8u));}
static uint64_t get_u64(const unsigned char *p){uint64_t v=0;unsigned i;for(i=0;i<8;i++)v|=(uint64_t)p[i]<<(i*8u);return v;}

fractal_result fractal_field_descriptor_validate(const fractal_field_descriptor*d,size_t element,size_t*required){size_t row;if(!d||!required||!element||!d->width||!d->height||d->format!=FRACTAL_FIELD_ITERATION_CLASSIFICATION_V1)return FRACTAL_ERROR_INVALID_SPEC;if(d->width>SIZE_MAX/element)return FRACTAL_ERROR_INVALID_SPEC;row=(size_t)d->width*element;if(d->stride<row||d->height>SIZE_MAX/d->stride)return FRACTAL_ERROR_INVALID_SPEC;*required=d->stride*d->height;return FRACTAL_OK;}
fractal_result fractal_field_view_validate(const fractal_field_view*v,size_t e){size_t n;if(!v||!v->data||fractal_field_descriptor_validate(&v->descriptor,e,&n)!=FRACTAL_OK||v->data_size<n)return FRACTAL_ERROR_INVALID_SPEC;return FRACTAL_OK;}
fractal_result fractal_mutable_field_view_validate(const fractal_mutable_field_view*v,size_t e){fractal_field_view x;if(!v)return FRACTAL_ERROR_INVALID_SPEC;x=(fractal_field_view){v->descriptor,v->data,v->data_size};return fractal_field_view_validate(&x,e);}

fractal_result fractal_analysis_request_serialize(const fractal_analysis_request*r,char*b,size_t c,size_t*l){int n;if(!r||!r->analyzer_id||!l||r->output_mode>FRACTAL_ANALYSIS_COPY_OUTPUT)return FRACTAL_ERROR_INVALID_SPEC;n=snprintf(b,c,"{\"analyzer\":\"%s\",\"mode\":%u,\"preserve\":%s,\"record_capacity\":%zu,\"records\":%s}",r->analyzer_id,(unsigned)r->output_mode,r->require_field_preservation?"true":"false",r->record_capacity,r->require_records?"true":"false");*l=n<0?0u:(size_t)n;return n<0||!b||c<=(size_t)n?FRACTAL_ERROR_BUFFER_TOO_SMALL:FRACTAL_OK;}
fractal_result fractal_analysis_pipeline_init(fractal_analysis_pipeline*p,const fractal_analyzer_vtable*a,const fractal_analysis_request*r){char s[256];size_t n;if(!p)return FRACTAL_ERROR_INVALID_ARGUMENT;memset(p,0,sizeof(*p));if(!a&&!r){p->identity=hash_bytes("analysis:none",13);return FRACTAL_OK;}if(!a||!r||!a->descriptor||strcmp(a->descriptor->module_id,r->analyzer_id)||fractal_module_descriptor_validate(a->descriptor,FRACTAL_MODULE_ANALYZER)!=FRACTAL_OK)return FRACTAL_ERROR_INVALID_SPEC;if(fractal_analysis_request_serialize(r,s,sizeof(s),&n)!=FRACTAL_OK)return FRACTAL_ERROR_INVALID_SPEC;p->count=1;p->analyzers[0]=a;p->requests[0]=*r;p->identity=hash_bytes(s,n);return FRACTAL_OK;}
fractal_result fractal_analysis_pipeline_serialize(const fractal_analysis_pipeline*p,char*b,size_t c,size_t*l){int n;if(!p||!l||p->count>1)return FRACTAL_ERROR_INVALID_SPEC;n=snprintf(b,c,"{\"analyzer\":\"%s\",\"count\":%zu,\"identity\":\"%016" PRIx64 "\"}",p->count?p->requests[0].analyzer_id:"",p->count,p->identity);*l=n<0?0u:(size_t)n;return n<0||!b||c<=(size_t)n?FRACTAL_ERROR_BUFFER_TOO_SMALL:FRACTAL_OK;}

fractal_result fractal_escape_summary_record_decode(const fractal_analysis_record*r,fractal_escape_classification_summary_v1*s){uint64_t *values[12];unsigned i;if(!r||!s||r->type_id!=FRACTAL_ANALYSIS_RECORD_ESCAPE_SUMMARY||r->schema_version!=FRACTAL_ESCAPE_SUMMARY_SCHEMA_VERSION||r->payload_size!=SUMMARY_PAYLOAD_SIZE)return FRACTAL_ERROR_INVALID_SPEC;memset(s,0,sizeof(*s));values[0]=&s->samples_total;values[1]=&s->escaped_samples;values[2]=&s->bounded_samples;values[3]=&s->unresolved_samples;values[4]=&s->maximum_iteration_samples;values[5]=&s->cancelled_samples;values[6]=&s->failed_samples;values[7]=&s->other_classified_samples;values[8]=&s->iteration_samples;values[9]=&s->iterations_min;values[10]=&s->iterations_max;values[11]=&s->iterations_sum;for(i=0;i<12;i++)*values[i]=get_u64(r->payload+i*8u);if(r->payload[96]>1)return FRACTAL_ERROR_INVALID_SPEC;s->iteration_statistics_valid=r->payload[96]!=0;return FRACTAL_OK;}
size_t fractal_iteration_histogram_bucket_v1(uint64_t v){size_t b;if(v<3)return (size_t)v;for(b=3;b<63;b++)if(v<=(UINT64_C(1)<<(b-1u)))return b;return 63u;}
fractal_result fractal_iteration_histogram_record_decode(const fractal_analysis_record*r,fractal_iteration_histogram_v1*h){uint64_t *values[7];unsigned i;if(!r||!h||r->type_id!=FRACTAL_ANALYSIS_RECORD_ITERATION_HISTOGRAM||r->schema_version!=FRACTAL_ITERATION_HISTOGRAM_SCHEMA_VERSION||r->payload_size!=HISTOGRAM_PAYLOAD_SIZE)return FRACTAL_ERROR_INVALID_SPEC;memset(h,0,sizeof(*h));for(i=0;i<64;i++)h->bins[i]=get_u64(r->payload+i*8u);values[0]=&h->eligible_samples;values[1]=&h->excluded_samples;values[2]=&h->total_samples;values[3]=&h->minimum_iteration;values[4]=&h->maximum_iteration;values[5]=&h->summed_iterations;values[6]=&h->overflow_bin_count;for(i=0;i<7;i++)*values[i]=get_u64(r->payload+512u+i*8u);if(r->payload[568]>1)return FRACTAL_ERROR_INVALID_SPEC;h->histogram_valid=r->payload[568]!=0;return FRACTAL_OK;}
fractal_result fractal_analysis_record_serialize(const fractal_analysis_record*r,char*b,size_t c,size_t*l){fractal_escape_classification_summary_v1 s;fractal_iteration_histogram_v1 h;int n;if(!l)return FRACTAL_ERROR_INVALID_SPEC;if(fractal_escape_summary_record_decode(r,&s)==FRACTAL_OK){n=snprintf(b,c,"{\"bounded_samples\":%" PRIu64 ",\"cancelled_samples\":%" PRIu64 ",\"escaped_samples\":%" PRIu64 ",\"failed_samples\":%" PRIu64 ",\"field_preserved\":true,\"iteration_samples\":%" PRIu64 ",\"iteration_statistics_valid\":%s,\"iterations_max\":%" PRIu64 ",\"iterations_min\":%" PRIu64 ",\"iterations_sum\":%" PRIu64 ",\"maximum_iteration_samples\":%" PRIu64 ",\"other_classified_samples\":%" PRIu64 ",\"samples_total\":%" PRIu64 ",\"schema\":\"%s\",\"schema_version\":1,\"unresolved_samples\":%" PRIu64 "}",s.bounded_samples,s.cancelled_samples,s.escaped_samples,s.failed_samples,s.iteration_samples,s.iteration_statistics_valid?"true":"false",s.iterations_max,s.iterations_min,s.iterations_sum,s.maximum_iteration_samples,s.other_classified_samples,s.samples_total,FRACTAL_ESCAPE_SUMMARY_SCHEMA_ID,s.unresolved_samples);}else if(fractal_iteration_histogram_record_decode(r,&h)==FRACTAL_OK){size_t used=0;unsigned i;n=snprintf(b,c,"{\"bin_count\":64,\"bins\":[");if(n<0)return FRACTAL_ERROR_INVALID_SPEC;used=(size_t)n;for(i=0;i<64;i++){n=snprintf(b&&used<c?b+used:NULL,used<c?c-used:0,"%s%" PRIu64,i?",":"",h.bins[i]);if(n<0)return FRACTAL_ERROR_INVALID_SPEC;used+=(size_t)n;}n=snprintf(b&&used<c?b+used:NULL,used<c?c-used:0,"],\"eligible_samples\":%" PRIu64 ",\"excluded_samples\":%" PRIu64 ",\"histogram_valid\":%s,\"maximum_iteration\":%" PRIu64 ",\"minimum_iteration\":%" PRIu64 ",\"overflow_bin_count\":%" PRIu64 ",\"schema\":\"%s\",\"schema_version\":1,\"summed_iterations\":%" PRIu64 ",\"total_samples\":%" PRIu64 "}",h.eligible_samples,h.excluded_samples,h.histogram_valid?"true":"false",h.maximum_iteration,h.minimum_iteration,h.overflow_bin_count,FRACTAL_ITERATION_HISTOGRAM_SCHEMA_ID,h.summed_iterations,h.total_samples);if(n<0)return FRACTAL_ERROR_INVALID_SPEC;used+=(size_t)n;*l=used;return !b||c<=used?FRACTAL_ERROR_BUFFER_TOO_SMALL:FRACTAL_OK;}else return FRACTAL_ERROR_INVALID_SPEC;*l=n<0?0u:(size_t)n;return n<0||!b||c<=(size_t)n?FRACTAL_ERROR_BUFFER_TOO_SMALL:FRACTAL_OK;}
fractal_result fractal_analysis_records_serialize(const fractal_analysis_record*r,size_t count,char*b,size_t c,size_t*l){char record[4096];size_t rn;int n;if(!l||(!r&&count)||count>1)return FRACTAL_ERROR_INVALID_ARGUMENT;if(!count){*l=2;if(!b||c<3)return FRACTAL_ERROR_BUFFER_TOO_SMALL;memcpy(b,"[]",3);return FRACTAL_OK;}if(fractal_analysis_record_serialize(r,record,sizeof(record),&rn)!=FRACTAL_OK)return FRACTAL_ERROR_INVALID_SPEC;n=snprintf(b,c,"[%s]",record);*l=n<0?0u:(size_t)n;return n<0||!b||c<=(size_t)n?FRACTAL_ERROR_BUFFER_TOO_SMALL:FRACTAL_OK;}
fractal_result fractal_analysis_result_serialize(const fractal_analysis_result*r,char*b,size_t c,size_t*l){int n;if(!r||!l)return FRACTAL_ERROR_INVALID_ARGUMENT;n=snprintf(b,c,"{\"analyzer\":\"%s\",\"cancelled\":%s,\"field_preserved\":%s,\"identity\":\"%016" PRIx64 "\",\"output_checksum\":\"%016" PRIx64 "\",\"records\":%zu,\"result\":%u,\"samples\":%" PRIu64 ",\"source_checksum\":\"%016" PRIx64 "\"}",r->analyzer_id?r->analyzer_id:"",r->cancelled?"true":"false",r->field_preserved?"true":"false",r->identity,r->output_field_checksum,r->records_produced,(unsigned)r->result,r->samples_examined,r->source_field_checksum);*l=n<0?0u:(size_t)n;return n<0||!b||c<=(size_t)n?FRACTAL_ERROR_BUFFER_TOO_SMALL:FRACTAL_OK;}

static fractal_result pass_validate(const fractal_analysis_request*r,const fractal_field_descriptor*d){size_t n;if(!r||!r->analyzer_id||strcmp(r->analyzer_id,"fractal.analyzer.passthrough")||r->require_records||r->output_mode>FRACTAL_ANALYSIS_COPY_OUTPUT)return FRACTAL_ERROR_INVALID_SPEC;return fractal_field_descriptor_validate(d,sizeof(fractal_point_result_compact),&n);}
static fractal_result common_begin(fractal_analyzer_state*s,const fractal_analysis_request*r,uint64_t checksum,const char*id){if(!s||!r||s->phase)return FRACTAL_ERROR_INVALID_ARGUMENT;memset(s,0,sizeof(*s));s->phase=1;s->request=*r;s->result.analyzer_id=id;s->result.analyzer_version=1;s->result.source_field_checksum=checksum;return FRACTAL_OK;}
static fractal_result pass_begin(fractal_analyzer_state*s,const fractal_analysis_request*r,uint64_t checksum){return common_begin(s,r,checksum,"fractal.analyzer.passthrough");}
static fractal_result pass_process(fractal_analyzer_state*s,const fractal_field_view*in,fractal_mutable_field_view*out,fractal_field_view*final,const fractal_cancellation*c){size_t n;if(!s||s->phase!=1||!final||fractal_field_view_validate(in,sizeof(fractal_point_result_compact))!=FRACTAL_OK)return FRACTAL_ERROR_INVALID_ARGUMENT;if(c&&c->requested){s->phase=3;s->result.cancelled=true;s->result.result=FRACTAL_ERROR_CANCELLED;return FRACTAL_ERROR_CANCELLED;}n=in->descriptor.stride*in->descriptor.height;if(out){uintptr_t a=(uintptr_t)in->data,z=a+n,b=(uintptr_t)out->data,w=b+out->data_size;if(fractal_mutable_field_view_validate(out,sizeof(fractal_point_result_compact))!=FRACTAL_OK||memcmp(&out->descriptor,&in->descriptor,sizeof(out->descriptor)))return FRACTAL_ERROR_INVALID_SPEC;if(a!=b&&a<w&&b<z)return FRACTAL_ERROR_INVALID_SPEC;if(a!=b)memcpy(out->data,in->data,n);*final=(fractal_field_view){out->descriptor,out->data,out->data_size};}else *final=*in;s->result.samples_examined=(uint64_t)in->descriptor.width*in->descriptor.height;s->result.output_field_checksum=fractal_checksum64(final->data,n);s->result.field_preserved=s->result.source_field_checksum==s->result.output_field_checksum;s->result.result=FRACTAL_OK;s->phase=2;return FRACTAL_OK;}
static fractal_result common_finish(fractal_analyzer_state*s,fractal_analysis_result*r){if(!s||!r||s->phase!=2)return FRACTAL_ERROR_INVALID_ARGUMENT;*r=s->result;s->phase=3;return FRACTAL_OK;}
static fractal_result pass_finish(fractal_analyzer_state*s,fractal_analysis_result*r){s->result.identity=s->result.output_field_checksum^s->result.samples_examined^UINT64_C(0x50545353);return common_finish(s,r);}
static void common_abort(fractal_analyzer_state*s){if(s&&s->phase&&s->phase!=3){s->result.records_produced=0;s->result.result=FRACTAL_ERROR_INVALID_SPEC;s->phase=3;}}
static const fractal_module_descriptor pass_desc={1,1,"fractal.analyzer.passthrough","Pass-through analyzer",FRACTAL_MODULE_ANALYZER,FRACTAL_CAP_ANALYZER_COMPATIBLE_FIELD|FRACTAL_CAP_ANALYZER_PRESERVES_FIELD_VALUES|FRACTAL_CAP_ANALYZER_CANCELLATION,true};
const fractal_analyzer_vtable fractal_analyzer_passthrough={&pass_desc,pass_validate,pass_begin,pass_process,pass_finish,common_abort};

static fractal_result summary_validate(const fractal_analysis_request*r,const fractal_field_descriptor*d){size_t n;if(!r||!r->analyzer_id||strcmp(r->analyzer_id,"fractal.analyzer.escape-classification-summary")||r->output_mode!=FRACTAL_ANALYSIS_BORROW_INPUT||!r->require_field_preservation||!r->require_records||r->record_capacity<1)return FRACTAL_ERROR_INVALID_SPEC;return fractal_field_descriptor_validate(d,sizeof(fractal_point_result_compact),&n);}
static fractal_result summary_begin(fractal_analyzer_state*s,const fractal_analysis_request*r,uint64_t checksum){return common_begin(s,r,checksum,"fractal.analyzer.escape-classification-summary");}
static void encode_summary(fractal_analysis_record*r,const fractal_escape_classification_summary_v1*s){const uint64_t values[12]={s->samples_total,s->escaped_samples,s->bounded_samples,s->unresolved_samples,s->maximum_iteration_samples,s->cancelled_samples,s->failed_samples,s->other_classified_samples,s->iteration_samples,s->iterations_min,s->iterations_max,s->iterations_sum};unsigned i;memset(r,0,sizeof(*r));r->type_id=FRACTAL_ANALYSIS_RECORD_ESCAPE_SUMMARY;r->schema_version=FRACTAL_ESCAPE_SUMMARY_SCHEMA_VERSION;r->payload_size=SUMMARY_PAYLOAD_SIZE;for(i=0;i<12;i++)put_u64(r->payload+i*8u,values[i]);r->payload[96]=(unsigned char)s->iteration_statistics_valid;}
static fractal_result summary_fail(fractal_analyzer_state*s,fractal_result q,bool cancelled){s->result.records_produced=0;s->result.result=q;s->result.cancelled=cancelled;s->phase=3;return q;}
static fractal_result summary_process(fractal_analyzer_state*s,const fractal_field_view*in,fractal_mutable_field_view*out,fractal_field_view*final,const fractal_cancellation*c){fractal_escape_classification_summary_v1 v={0};uint32_t y,x;uint64_t expected;if(!s||s->phase!=1||!final||out||fractal_field_view_validate(in,sizeof(fractal_point_result_compact))!=FRACTAL_OK)return FRACTAL_ERROR_INVALID_ARGUMENT;expected=(uint64_t)in->descriptor.width*in->descriptor.height;if(c&&c->requested)return summary_fail(s,FRACTAL_ERROR_CANCELLED,true);for(y=0;y<in->descriptor.height;y++){if(c&&c->requested)return summary_fail(s,FRACTAL_ERROR_CANCELLED,true);for(x=0;x<in->descriptor.width;x++){const fractal_point_result_compact*p=(const fractal_point_result_compact*)((const unsigned char*)in->data+(size_t)y*in->descriptor.stride)+x;uint64_t *counter=NULL;bool eligible=false;if(!add_u64(&v.samples_total,1)||!add_u64(&s->result.samples_examined,1))return summary_fail(s,FRACTAL_ERROR_INVALID_SPEC,false);switch(p->classification){case FRACTAL_CLASS_ESCAPED:counter=&v.escaped_samples;eligible=true;break;case FRACTAL_CLASS_BOUNDED:counter=&v.bounded_samples;eligible=true;break;case FRACTAL_CLASS_UNRESOLVED:counter=&v.unresolved_samples;eligible=true;if(!add_u64(&v.maximum_iteration_samples,1))return summary_fail(s,FRACTAL_ERROR_INVALID_SPEC,false);break;case FRACTAL_CLASS_CANCELLED:counter=&v.cancelled_samples;break;case FRACTAL_CLASS_FAILED:counter=&v.failed_samples;break;default:return summary_fail(s,FRACTAL_ERROR_INVALID_SPEC,false);}if(!add_u64(counter,1))return summary_fail(s,FRACTAL_ERROR_INVALID_SPEC,false);if(eligible){if(!v.iteration_statistics_valid){v.iterations_min=p->steps;v.iterations_max=p->steps;v.iteration_statistics_valid=true;}else{if(p->steps<v.iterations_min)v.iterations_min=p->steps;if(p->steps>v.iterations_max)v.iterations_max=p->steps;}if(!add_u64(&v.iteration_samples,1)||!add_u64(&v.iterations_sum,p->steps))return summary_fail(s,FRACTAL_ERROR_INVALID_SPEC,false);}}}if(v.samples_total!=expected||v.escaped_samples+v.bounded_samples+v.unresolved_samples+v.cancelled_samples+v.failed_samples+v.other_classified_samples!=v.samples_total)return summary_fail(s,FRACTAL_ERROR_INVALID_SPEC,false);encode_summary(&s->result.records[0],&v);{char canonical[1024];size_t length;if(fractal_analysis_record_serialize(&s->result.records[0],canonical,sizeof(canonical),&length)!=FRACTAL_OK)return summary_fail(s,FRACTAL_ERROR_INVALID_SPEC,false);s->result.records[0].identity=hash_bytes(canonical,length);s->result.identity=s->result.records[0].identity;}*final=*in;s->result.records_produced=1;s->result.output_field_checksum=fractal_checksum64(in->data,in->descriptor.stride*in->descriptor.height);s->result.field_preserved=s->result.output_field_checksum==s->result.source_field_checksum;s->result.result=FRACTAL_OK;s->phase=2;return FRACTAL_OK;}
static const fractal_module_descriptor summary_desc={1,1,"fractal.analyzer.escape-classification-summary","Escape and classification summary",FRACTAL_MODULE_ANALYZER,FRACTAL_CAP_ANALYZER_COMPATIBLE_FIELD|FRACTAL_CAP_ANALYZER_PRESERVES_FIELD_VALUES|FRACTAL_CAP_ANALYZER_CANCELLATION|FRACTAL_CAP_ANALYZER_PRODUCES_RECORDS|FRACTAL_CAP_ANALYZER_WHOLE_FIELD,true};
const fractal_analyzer_vtable fractal_analyzer_escape_classification_summary={&summary_desc,summary_validate,summary_begin,summary_process,common_finish,common_abort};

static fractal_result histogram_validate(const fractal_analysis_request*r,const fractal_field_descriptor*d){size_t n;if(!r||!r->analyzer_id||strcmp(r->analyzer_id,"fractal.analyzer.iteration-histogram")||r->output_mode!=FRACTAL_ANALYSIS_BORROW_INPUT||!r->require_field_preservation||!r->require_records||r->record_capacity<1)return FRACTAL_ERROR_INVALID_SPEC;return fractal_field_descriptor_validate(d,sizeof(fractal_point_result_compact),&n);}
static fractal_result histogram_begin(fractal_analyzer_state*s,const fractal_analysis_request*r,uint64_t checksum){return common_begin(s,r,checksum,"fractal.analyzer.iteration-histogram");}
static void encode_histogram(fractal_analysis_record*r,const fractal_iteration_histogram_v1*h){uint64_t values[7]={h->eligible_samples,h->excluded_samples,h->total_samples,h->minimum_iteration,h->maximum_iteration,h->summed_iterations,h->overflow_bin_count};unsigned i;memset(r,0,sizeof(*r));r->type_id=FRACTAL_ANALYSIS_RECORD_ITERATION_HISTOGRAM;r->schema_version=1;r->payload_size=HISTOGRAM_PAYLOAD_SIZE;for(i=0;i<64;i++)put_u64(r->payload+i*8u,h->bins[i]);for(i=0;i<7;i++)put_u64(r->payload+512u+i*8u,values[i]);r->payload[568]=(unsigned char)h->histogram_valid;}
static fractal_result histogram_process(fractal_analyzer_state*s,const fractal_field_view*in,fractal_mutable_field_view*out,fractal_field_view*final,const fractal_cancellation*c){fractal_iteration_histogram_v1 h={0};uint32_t x,y;uint64_t expected;if(!s||s->phase!=1||!final||out||fractal_field_view_validate(in,sizeof(fractal_point_result_compact))!=FRACTAL_OK)return FRACTAL_ERROR_INVALID_ARGUMENT;expected=(uint64_t)in->descriptor.width*in->descriptor.height;if(c&&c->requested)return summary_fail(s,FRACTAL_ERROR_CANCELLED,true);for(y=0;y<in->descriptor.height;y++){if(c&&c->requested)return summary_fail(s,FRACTAL_ERROR_CANCELLED,true);for(x=0;x<in->descriptor.width;x++){const fractal_point_result_compact*p=(const fractal_point_result_compact*)((const unsigned char*)in->data+(size_t)y*in->descriptor.stride)+x;bool eligible;if(!add_u64(&h.total_samples,1)||!add_u64(&s->result.samples_examined,1))return summary_fail(s,FRACTAL_ERROR_INVALID_SPEC,false);switch(p->classification){case FRACTAL_CLASS_ESCAPED:case FRACTAL_CLASS_BOUNDED:case FRACTAL_CLASS_UNRESOLVED:eligible=true;break;case FRACTAL_CLASS_CANCELLED:case FRACTAL_CLASS_FAILED:eligible=false;break;default:return summary_fail(s,FRACTAL_ERROR_INVALID_SPEC,false);}if(!eligible){if(!add_u64(&h.excluded_samples,1))return summary_fail(s,FRACTAL_ERROR_INVALID_SPEC,false);continue;}if(!h.histogram_valid){h.minimum_iteration=h.maximum_iteration=p->steps;h.histogram_valid=true;}else{if(p->steps<h.minimum_iteration)h.minimum_iteration=p->steps;if(p->steps>h.maximum_iteration)h.maximum_iteration=p->steps;}if(!add_u64(&h.eligible_samples,1)||!add_u64(&h.summed_iterations,p->steps)||!add_u64(&h.bins[fractal_iteration_histogram_bucket_v1(p->steps)],1))return summary_fail(s,FRACTAL_ERROR_INVALID_SPEC,false);}}h.overflow_bin_count=h.bins[63];if(h.total_samples!=expected||h.eligible_samples+h.excluded_samples!=h.total_samples)return summary_fail(s,FRACTAL_ERROR_INVALID_SPEC,false);encode_histogram(&s->result.records[0],&h);{char canonical[4096];size_t length;if(fractal_analysis_record_serialize(&s->result.records[0],canonical,sizeof(canonical),&length)!=FRACTAL_OK)return summary_fail(s,FRACTAL_ERROR_INVALID_SPEC,false);s->result.records[0].identity=hash_bytes(canonical,length);s->result.identity=s->result.records[0].identity;}*final=*in;s->result.records_produced=1;s->result.output_field_checksum=fractal_checksum64(in->data,in->descriptor.stride*in->descriptor.height);s->result.field_preserved=s->result.output_field_checksum==s->result.source_field_checksum;s->result.result=FRACTAL_OK;s->phase=2;return FRACTAL_OK;}
static const fractal_module_descriptor histogram_desc={1,1,"fractal.analyzer.iteration-histogram","Fixed-schema iteration histogram",FRACTAL_MODULE_ANALYZER,FRACTAL_CAP_ANALYZER_COMPATIBLE_FIELD|FRACTAL_CAP_ANALYZER_PRESERVES_FIELD_VALUES|FRACTAL_CAP_ANALYZER_CANCELLATION|FRACTAL_CAP_ANALYZER_PRODUCES_RECORDS|FRACTAL_CAP_ANALYZER_WHOLE_FIELD,true};
const fractal_analyzer_vtable fractal_analyzer_iteration_histogram={&histogram_desc,histogram_validate,histogram_begin,histogram_process,common_finish,common_abort};
