#include "fractal/module_registry.h"
#include <stdio.h>
#include <string.h>
static int before(const fractal_module_registration *a,const fractal_module_registration *b){
 if(a->descriptor->kind!=b->descriptor->kind)return a->descriptor->kind<b->descriptor->kind;
 return strcmp(a->descriptor->module_id,b->descriptor->module_id)<0;
}
static void hash_bytes(uint64_t *h,const void *v,size_t n){const unsigned char*p=v;while(n--){*h^=*p++;*h*=UINT64_C(1099511628211);}}
static void hash_text(uint64_t*h,const char*s){hash_bytes(h,s,strlen(s)+1u);}
fractal_result fractal_module_registry_init(fractal_module_registry*r,const fractal_module_registration*m,size_t n){size_t i,j;if(!r||(!m&&n)||n>FRACTAL_REGISTRY_MAX_MODULES)return FRACTAL_ERROR_INVALID_ARGUMENT;memset(r,0,sizeof(*r));for(i=0;i<n;i++){if(!m[i].descriptor||!m[i].implementation||fractal_module_descriptor_validate(m[i].descriptor,m[i].descriptor->kind)!=FRACTAL_OK)return FRACTAL_ERROR_INVALID_SPEC;r->entries[i]=m[i];}r->count=n;for(i=1;i<n;i++){fractal_module_registration x=r->entries[i];j=i;while(j&&before(&x,&r->entries[j-1])){r->entries[j]=r->entries[j-1];j--;}r->entries[j]=x;}for(i=1;i<n;i++)if(r->entries[i-1].descriptor->kind==r->entries[i].descriptor->kind&&!strcmp(r->entries[i-1].descriptor->module_id,r->entries[i].descriptor->module_id))return FRACTAL_ERROR_INVALID_SPEC;r->identity=UINT64_C(1469598103934665603);for(i=0;i<n;i++){const fractal_module_descriptor*d=r->entries[i].descriptor;hash_bytes(&r->identity,&d->kind,sizeof(d->kind));hash_text(&r->identity,d->module_id);hash_bytes(&r->identity,&d->abi_version,sizeof(d->abi_version));hash_bytes(&r->identity,&d->module_version,sizeof(d->module_version));hash_bytes(&r->identity,&d->available,sizeof(d->available));hash_bytes(&r->identity,&d->capability_flags,sizeof(d->capability_flags));}return FRACTAL_OK;}
size_t fractal_module_registry_total_count(const fractal_module_registry*r){return r?r->count:0;}
size_t fractal_module_registry_count(const fractal_module_registry*r,fractal_module_kind k){size_t i,n=0;if(!r)return 0;for(i=0;i<r->count;i++)n+=r->entries[i].descriptor->kind==k;return n;}
const fractal_module_descriptor*fractal_module_registry_at(const fractal_module_registry*r,fractal_module_kind k,size_t x){size_t i;if(!r)return NULL;for(i=0;i<r->count;i++)if(r->entries[i].descriptor->kind==k&&!x--)return r->entries[i].descriptor;return NULL;}
const fractal_module_descriptor*fractal_module_registry_find(const fractal_module_registry*r,fractal_module_kind k,const char*id){size_t i;if(!r||!id)return NULL;for(i=0;i<r->count;i++)if(r->entries[i].descriptor->kind==k&&!strcmp(r->entries[i].descriptor->module_id,id))return r->entries[i].descriptor;return NULL;}
const void*fractal_module_registry_implementation(const fractal_module_registry*r,fractal_module_kind k,const char*id){size_t i;if(!r||!id)return NULL;for(i=0;i<r->count;i++)if(r->entries[i].descriptor->kind==k&&!strcmp(r->entries[i].descriptor->module_id,id))return r->entries[i].implementation;return NULL;}
uint64_t fractal_module_registry_identity(const fractal_module_registry*r){return r?r->identity:0;}
fractal_result fractal_module_registry_serialize(const fractal_module_registry*r,char*b,size_t c,size_t*l){size_t used=0,i;int n;if(!r||!l||(!b&&c))return FRACTAL_ERROR_INVALID_ARGUMENT;n=snprintf(b,c,"{\"identity\":\"%016llx\",\"modules\":[",(unsigned long long)r->identity);if(n<0)return FRACTAL_ERROR_IO;used=(size_t)n;for(i=0;i<r->count;i++){const fractal_module_descriptor*d=r->entries[i].descriptor;n=snprintf(b&&used<c?b+used:NULL,used<c?c-used:0,"%s{\"available\":%s,\"capabilities\":\"%016llx\",\"id\":\"%s\",\"kind\":\"%s\",\"module_version\":%u}",i?",":"",d->available?"true":"false",(unsigned long long)d->capability_flags,d->module_id,fractal_module_kind_string(d->kind),d->module_version);if(n<0)return FRACTAL_ERROR_IO;used+=(size_t)n;}n=snprintf(b&&used<c?b+used:NULL,used<c?c-used:0,"]}");if(n<0)return FRACTAL_ERROR_IO;used+=(size_t)n;*l=used;return !b||c<=used?FRACTAL_ERROR_BUFFER_TOO_SMALL:FRACTAL_OK;}
