#include "fractal/pairing.h"
#include <stddef.h>
#include <string.h>

static uint64_t p_hash_bytes(uint64_t hash, const void *data, size_t size) { const unsigned char *b = (const unsigned char *)data; size_t i; for (i = 0u; i < size; ++i) { hash ^= b[i]; hash *= UINT64_C(1099511628211); } return hash; }
static uint64_t p_hash_u64(uint64_t hash, uint64_t value) { unsigned int s; for (s = 0u; s < 64u; s += 8u) { unsigned char byte = (unsigned char)(value >> s); hash = p_hash_bytes(hash, &byte, 1u); } return hash; }
static bool p_id_zero(fractal_workspace_id id) { return id.high == 0u && id.low == 0u; }
bool fractal_pairing_id_equal(fractal_workspace_id left, fractal_workspace_id right) { return left.high == right.high && left.low == right.low; }
static fractal_workspace_id p_make_id(uint64_t domain, uint64_t a, uint64_t b, uint64_t c) { fractal_workspace_id id; uint64_t h = UINT64_C(1469598103934665603); h = p_hash_u64(p_hash_u64(p_hash_u64(p_hash_u64(h, domain), a), b), c); id.high = h; id.low = p_hash_u64(h, UINT64_C(0x50414952494e47)); return id; }
static bool nonce_equal(fractal_pairing_nonce a, fractal_pairing_nonce b) { return memcmp(a.bytes, b.bytes, sizeof(a.bytes)) == 0; }
static bool nonce_zero(fractal_pairing_nonce n) { static const fractal_pairing_nonce z; return nonce_equal(n, z); }
static bool remember_nonce(fractal_pairing_state *state, fractal_pairing_nonce nonce) { uint32_t i; if (nonce_zero(nonce)) return false; for (i = 0u; i < state->seen_nonce_count; ++i) if (nonce_equal(state->seen_nonces[i], nonce)) return false; if (state->seen_nonce_count >= 16u) return false; state->seen_nonces[state->seen_nonce_count++] = nonce; return true; }

fractal_pairing_invitation fractal_pairing_invitation_create(fractal_service_id service_id, uint32_t service_key_version, fractal_participant_role role, fractal_workspace_capabilities ceiling, uint64_t created_tick, uint64_t expires_tick, fractal_pairing_nonce nonce, uint32_t human_code) { fractal_pairing_invitation out; uint64_t h = UINT64_C(1469598103934665603); memset(&out, 0, sizeof(out)); out.service_id = service_id; out.service_key_version = service_key_version; out.requested_role = role; out.capability_ceiling = ceiling; out.created_tick = created_tick; out.expires_tick = expires_tick; out.nonce = nonce; out.human_code = human_code; out.status = FRACTAL_INVITATION_CREATED; out.brute_force_limit = 5u; h = p_hash_u64(p_hash_u64(h, service_id.high), service_id.low); h = p_hash_u64(p_hash_u64(p_hash_u64(h, service_key_version), role), ceiling); h = p_hash_bytes(h, nonce.bytes, sizeof(nonce.bytes)); out.id = p_make_id(UINT64_C(0x494e56495445), h, created_tick, expires_tick); out.identity = out.id; return out; }

fractal_transcript_id fractal_pairing_message_identity(const fractal_pairing_message *m) { uint64_t h = UINT64_C(1469598103934665603); fractal_transcript_id id = {0u, 0u}; if (m == NULL) return id; h = p_hash_u64(p_hash_u64(h, m->protocol_version), m->kind); h = p_hash_u64(p_hash_u64(h, m->handshake_id.high), m->handshake_id.low); h = p_hash_u64(p_hash_u64(h, m->service_id.high), m->service_id.low); h = p_hash_u64(p_hash_u64(h, m->device_id.high), m->device_id.low); h = p_hash_u64(p_hash_u64(h, m->invitation_id.high), m->invitation_id.low); h = p_hash_u64(p_hash_u64(h, m->previous_transcript.high), m->previous_transcript.low); h = p_hash_bytes(h, m->nonce.bytes, sizeof(m->nonce.bytes)); h = p_hash_u64(p_hash_u64(h, m->sequence), m->expires_tick); id.high = h; id.low = p_hash_u64(h, UINT64_C(0x5452414e534352)); return id; }

int fractal_pairing_state_init(fractal_pairing_state *state, fractal_service_identity service, fractal_pairing_invitation invitation) { if (state == NULL || p_id_zero(service.id) || p_id_zero(invitation.id) || !fractal_pairing_id_equal(service.id, invitation.service_id)) return -1; memset(state, 0, sizeof(*state)); state->protocol_version = FRACTAL_PAIRING_PROTOCOL_VERSION; state->service = service; state->invitation = invitation; state->stage = FRACTAL_PAIRING_UNKNOWN; state->next_sequence = 1u; return 0; }

static fractal_pairing_rejection validate_common(fractal_pairing_state *s, const fractal_pairing_message *m, uint64_t now) { if (s == NULL || m == NULL || p_id_zero(m->handshake_id) || m->sequence != s->next_sequence || m->kind > FRACTAL_PAIRING_COMPLETE) return FRACTAL_PAIRING_REJECT_STRUCTURE; if (m->protocol_version != FRACTAL_PAIRING_PROTOCOL_VERSION) return FRACTAL_PAIRING_REJECT_VERSION; if (m->expires_tick != 0u && now > m->expires_tick) return FRACTAL_PAIRING_REJECT_INVITATION; if (!fractal_pairing_id_equal(m->service_id, s->service.id) || !fractal_pairing_id_equal(m->invitation_id, s->invitation.id)) return FRACTAL_PAIRING_REJECT_IDENTITY; if (s->invitation.status == FRACTAL_INVITATION_REVOKED || s->invitation.status == FRACTAL_INVITATION_DENIED || (s->invitation.used && !(s->stage == FRACTAL_PAIRING_CREDENTIAL_ISSUED && m->kind == FRACTAL_PAIRING_COMPLETE))) return FRACTAL_PAIRING_REJECT_INVITATION; if (now > s->invitation.expires_tick) { s->invitation.status = FRACTAL_INVITATION_EXPIRED; return FRACTAL_PAIRING_REJECT_INVITATION; } if (s->next_sequence > 1u && !fractal_pairing_id_equal(m->previous_transcript, s->transcript)) return FRACTAL_PAIRING_REJECT_TRANSCRIPT; return FRACTAL_PAIRING_REJECT_NONE; }
static bool ceiling_ok(fractal_pairing_state *s, fractal_workspace_capabilities caps) { const fractal_workspace_capabilities forbidden = FRACTAL_CAP_ADMIN; return (caps & ~s->invitation.capability_ceiling) == 0u && (caps & forbidden) == 0u; }
static void accept_message(fractal_pairing_state *s, const fractal_pairing_message *m, fractal_pairing_transition *t) { s->transcript = fractal_pairing_message_identity(m); s->next_sequence++; t->accepted = true; t->rejection = FRACTAL_PAIRING_REJECT_NONE; t->transcript = s->transcript; }

fractal_pairing_transition fractal_pairing_reduce(fractal_pairing_state *s, const fractal_pairing_message *m, uint64_t now) { fractal_pairing_transition t; fractal_pairing_rejection r; memset(&t, 0, sizeof(t)); t.rejection = FRACTAL_PAIRING_REJECT_STRUCTURE; if (s == NULL) return t; t.previous_stage = s->stage; t.resulting_stage = s->stage; r = validate_common(s, m, now); if (r != FRACTAL_PAIRING_REJECT_NONE) { t.rejection = r; if (r != FRACTAL_PAIRING_REJECT_STRUCTURE) s->stage = FRACTAL_PAIRING_FAILED; t.resulting_stage = s->stage; return t; }
    if (!remember_nonce(s, m->nonce)) { t.rejection = FRACTAL_PAIRING_REJECT_NONCE_REPLAY; s->stage = FRACTAL_PAIRING_FAILED; t.resulting_stage = s->stage; return t; }
    if (m->kind == FRACTAL_PAIRING_CLIENT_HELLO && s->stage == FRACTAL_PAIRING_UNKNOWN) { s->handshake_id = m->handshake_id; s->stage = FRACTAL_PAIRING_DISCOVERED; }
    else if (m->kind == FRACTAL_PAIRING_SERVICE_HELLO && s->stage == FRACTAL_PAIRING_DISCOVERED && fractal_pairing_id_equal(m->handshake_id, s->handshake_id)) { s->stage = FRACTAL_PAIRING_INVITATION_PRESENTED; s->invitation.status = FRACTAL_INVITATION_ADVERTISED; }
    else if (m->kind == FRACTAL_PAIRING_DEVICE_ENROLLMENT_REQUEST && s->stage == FRACTAL_PAIRING_INVITATION_PRESENTED) { if (p_id_zero(m->device_id)) { t.rejection = FRACTAL_PAIRING_REJECT_IDENTITY; s->stage = FRACTAL_PAIRING_FAILED; t.resulting_stage = s->stage; return t; } s->device = m->payload.device; s->device.id = m->device_id; s->device.enrollment = FRACTAL_ENROLLMENT_PENDING; s->invitation.status = FRACTAL_INVITATION_CLAIMED; }
    else if (m->kind == FRACTAL_PAIRING_SERVICE_CHALLENGE && s->stage == FRACTAL_PAIRING_INVITATION_PRESENTED) { }
    else if (m->kind == FRACTAL_PAIRING_DEVICE_PROOF && s->stage == FRACTAL_PAIRING_INVITATION_PRESENTED) { if (!m->prevalidated_proof) { t.rejection = FRACTAL_PAIRING_REJECT_PROOF; s->stage = FRACTAL_PAIRING_FAILED; t.resulting_stage = s->stage; return t; } s->device_proof_verified = true; }
    else if (m->kind == FRACTAL_PAIRING_SERVICE_PROOF && s->device_proof_verified) { if (!m->prevalidated_proof) { t.rejection = FRACTAL_PAIRING_REJECT_PROOF; s->stage = FRACTAL_PAIRING_FAILED; t.resulting_stage = s->stage; return t; } s->service_proof_verified = true; s->stage = FRACTAL_PAIRING_KEY_PROOF_VERIFIED; }
    else if (m->kind == FRACTAL_PAIRING_HUMAN_VERIFICATION_PENDING && s->stage == FRACTAL_PAIRING_KEY_PROOF_VERIFIED) { if (m->payload.approval.code != s->invitation.human_code) { s->invitation.failed_attempts++; t.rejection = FRACTAL_PAIRING_REJECT_HUMAN_VERIFICATION; if (s->invitation.failed_attempts >= s->invitation.brute_force_limit) s->stage = FRACTAL_PAIRING_FAILED; t.resulting_stage = s->stage; return t; } s->human_verified = true; s->stage = FRACTAL_PAIRING_HUMAN_CONFIRMATION_REQUIRED; }
    else if (m->kind == FRACTAL_PAIRING_APPROVAL && s->stage == FRACTAL_PAIRING_HUMAN_CONFIRMATION_REQUIRED) { if (!m->payload.approval.approved) { s->invitation.status = FRACTAL_INVITATION_DENIED; t.rejection = FRACTAL_PAIRING_REJECT_DENIED; s->stage = FRACTAL_PAIRING_FAILED; t.resulting_stage = s->stage; return t; } if (!ceiling_ok(s, m->payload.approval.capabilities)) { t.rejection = FRACTAL_PAIRING_REJECT_CAPABILITY; s->stage = FRACTAL_PAIRING_FAILED; t.resulting_stage = s->stage; return t; } s->device.participant_id = p_make_id(UINT64_C(0x50415254494349), m->device_id.high, m->device_id.low, m->sequence); s->device.enrollment = FRACTAL_ENROLLMENT_APPROVED; s->invitation.status = FRACTAL_INVITATION_APPROVED; s->stage = FRACTAL_PAIRING_APPROVED; }
    else if (m->kind == FRACTAL_PAIRING_CREDENTIAL_ISSUANCE && s->stage == FRACTAL_PAIRING_APPROVED) { fractal_pairing_credential *c; if (s->credential_count >= FRACTAL_PAIRING_CREDENTIAL_CAPACITY) { t.rejection = FRACTAL_PAIRING_REJECT_CAPACITY; s->stage = FRACTAL_PAIRING_FAILED; t.resulting_stage = s->stage; return t; } if (!ceiling_ok(s, m->payload.credential.capabilities)) { t.rejection = FRACTAL_PAIRING_REJECT_CAPABILITY; s->stage = FRACTAL_PAIRING_FAILED; t.resulting_stage = s->stage; return t; } c = &s->credentials[s->credential_count++]; *c = m->payload.credential; c->id = p_make_id(UINT64_C(0x43524544454e54), m->device_id.high, m->sequence, now); c->participant_id = s->device.participant_id; c->device_id = m->device_id; c->service_id = s->service.id; c->service_key_version = s->service.key_version; c->device_key_version = s->device.key_version; c->status = FRACTAL_CREDENTIAL_ACTIVE; s->invitation.status = FRACTAL_INVITATION_CONSUMED; s->invitation.used = true; s->stage = FRACTAL_PAIRING_CREDENTIAL_ISSUED; t.credential_issued = true; t.credential_id = c->id; }
    else if (m->kind == FRACTAL_PAIRING_COMPLETE && s->stage == FRACTAL_PAIRING_CREDENTIAL_ISSUED) { s->stage = FRACTAL_PAIRING_ACTIVE; }
    else { t.rejection = FRACTAL_PAIRING_REJECT_ORDER; s->stage = FRACTAL_PAIRING_FAILED; t.resulting_stage = s->stage; return t; }
    accept_message(s, m, &t); t.resulting_stage = s->stage; return t; }

int fractal_pairing_revoke_credential(fractal_pairing_state *state, fractal_credential_id credential_id, uint64_t revocation_epoch) { uint32_t i; if (state == NULL || p_id_zero(credential_id)) return -1; for (i = 0u; i < state->credential_count; ++i) if (fractal_pairing_id_equal(state->credentials[i].id, credential_id)) { state->credentials[i].status = FRACTAL_CREDENTIAL_REVOKED; state->credentials[i].revocation_epoch = revocation_epoch; state->revocation_epoch = revocation_epoch; return 0; } return -1; }
