#include "fractal/protocol_security.h"
#include <string.h>
static void put16(uint8_t*p,uint16_t v){p[0]=(uint8_t)(v>>8);p[1]=(uint8_t)v;}static void put32(uint8_t*p,uint32_t v){p[0]=(uint8_t)(v>>24);p[1]=(uint8_t)(v>>16);p[2]=(uint8_t)(v>>8);p[3]=(uint8_t)v;}static void put64(uint8_t*p,uint64_t v){uint32_t i;for(i=0;i<8;i++)p[i]=(uint8_t)(v>>(56u-8u*i));}static uint16_t get16(const uint8_t*p){return (uint16_t)(((uint16_t)p[0]<<8)|p[1]);}static uint32_t get32(const uint8_t*p){return ((uint32_t)p[0]<<24)|((uint32_t)p[1]<<16)|((uint32_t)p[2]<<8)|p[3];}static uint64_t get64(const uint8_t*p){uint64_t v=0;uint32_t i;for(i=0;i<8;i++)v=(v<<8)|p[i];return v;}
fractal_transport_security_rejection fractal_security_policy_validate(fractal_security_policy p){if(p.remote&&p.cleartext)return FRACTAL_SECURITY_REJECT_CLEARTEXT;if(p.tls_version!=FRACTAL_TLS_VERSION_TLS13)return FRACTAL_SECURITY_REJECT_TLS_VERSION;if(p.zero_rtt&&p.mutating_intent)return FRACTAL_SECURITY_REJECT_ZERO_RTT_MUTATION;if(p.cipher!=FRACTAL_CIPHER_TLS_AES_256_GCM_SHA384&&p.cipher!=FRACTAL_CIPHER_TLS13_POLICY_AEAD_FALLBACK)return FRACTAL_SECURITY_REJECT_CIPHER;if(!p.service_identity_present)return FRACTAL_SECURITY_REJECT_MISSING_SERVICE_IDENTITY;if(p.service_key_replaced_without_rotation)return FRACTAL_SECURITY_REJECT_SERVICE_KEY_REPLACEMENT;if(!p.credential_proof_present)return FRACTAL_SECURITY_REJECT_UNPROVED_CREDENTIAL;return FRACTAL_SECURITY_ACCEPTED;}
fractal_result fractal_frame_encode(fractal_protocol_frame_header h,const uint8_t*payload,uint8_t*out,uint32_t cap,uint32_t*w){uint32_t need=20u+h.payload_length;if(!out||!w||h.magic!=FRACTAL_PROTOCOL_FRAME_MAGIC||h.version!=FRACTAL_PROTOCOL_FRAME_VERSION||h.payload_length>FRACTAL_PROTOCOL_MAX_PAYLOAD||need<h.payload_length||cap<need||(!payload&&h.payload_length))return FRACTAL_ERROR_INVALID_ARGUMENT;put32(out,h.magic);put16(out+4,h.version);put16(out+6,h.message_class);put16(out+8,h.flags);put32(out+10,h.payload_length);put64(out+14,h.session_sequence);if(h.payload_length)memcpy(out+20,payload,h.payload_length);*w=need;return FRACTAL_OK;}
fractal_result fractal_frame_decode(const uint8_t*b,uint32_t len,fractal_protocol_frame_header*h,const uint8_t**payload){uint32_t plen;if(!b||!h||!payload||len<20)return FRACTAL_ERROR_INVALID_ARGUMENT;h->magic=get32(b);h->version=get16(b+4);h->message_class=get16(b+6);h->flags=get16(b+8);plen=get32(b+10);h->payload_length=plen;h->session_sequence=get64(b+14);if(h->magic!=FRACTAL_PROTOCOL_FRAME_MAGIC||h->version!=FRACTAL_PROTOCOL_FRAME_VERSION||plen>FRACTAL_PROTOCOL_MAX_PAYLOAD||len!=20u+plen)return FRACTAL_ERROR_INVALID_ARGUMENT;*payload=b+20;return FRACTAL_OK;}
static fractal_result cbor_uint(uint64_t v,uint8_t*out,uint32_t cap,uint32_t*w){if(v<24){if(cap<1)return FRACTAL_ERROR_BUFFER_TOO_SMALL;out[0]=(uint8_t)v;*w=1;return FRACTAL_OK;}if(v<=0xff){if(cap<2)return FRACTAL_ERROR_BUFFER_TOO_SMALL;out[0]=0x18;out[1]=(uint8_t)v;*w=2;return FRACTAL_OK;}if(v<=0xffff){if(cap<3)return FRACTAL_ERROR_BUFFER_TOO_SMALL;out[0]=0x19;put16(out+1,(uint16_t)v);*w=3;return FRACTAL_OK;}if(v<=0xffffffffu){if(cap<5)return FRACTAL_ERROR_BUFFER_TOO_SMALL;out[0]=0x1a;put32(out+1,(uint32_t)v);*w=5;return FRACTAL_OK;}if(cap<9)return FRACTAL_ERROR_BUFFER_TOO_SMALL;out[0]=0x1b;put64(out+1,v);*w=9;return FRACTAL_OK;}
static int read_uint(const uint8_t*b,uint32_t len,uint32_t*off,uint64_t*v){uint8_t h;if(*off>=len)return 0;h=b[(*off)++];if((h&0xe0)!=0)return 0;h&=0x1f;if(h<24){*v=h;return 1;}if(h==24&&*off<len){*v=b[(*off)++];return *v>=24;}if(h==25&&*off+1<len){*v=get16(b+*off);*off+=2;return *v>0xff;}if(h==26&&*off+3<len){*v=get32(b+*off);*off+=4;return *v>0xffff;}if(h==27&&*off+7<len){*v=get64(b+*off);*off+=8;return *v>0xffffffffu;}return 0;}
fractal_result fractal_cbor_encode_uint_map(const fractal_cbor_map*m,uint8_t*out,uint32_t cap,uint32_t*w){uint32_t i,off=1,n;if(!m||!out||!w||m->count>FRACTAL_PROTOCOL_MAX_FIELDS||m->count>23||cap<1)return FRACTAL_ERROR_INVALID_ARGUMENT;for(i=1;i<m->count;i++)if(m->fields[i-1].key>=m->fields[i].key)return FRACTAL_ERROR_INVALID_ARGUMENT;out[0]=(uint8_t)(0xa0|m->count);for(i=0;i<m->count;i++){if(cbor_uint(m->fields[i].key,out+off,cap-off,&n)!=FRACTAL_OK)return FRACTAL_ERROR_BUFFER_TOO_SMALL;off+=n;if(cbor_uint(m->fields[i].value,out+off,cap-off,&n)!=FRACTAL_OK)return FRACTAL_ERROR_BUFFER_TOO_SMALL;off+=n;}*w=off;return FRACTAL_OK;}
fractal_result fractal_cbor_decode_uint_map(const uint8_t*b,uint32_t len,fractal_cbor_map*m,bool reject_required){uint32_t off=1,i;uint8_t n;uint64_t k,v;if(!b||!m||len<1||(b[0]&0xf0)!=0xa0||(b[0]&0x1f)>FRACTAL_PROTOCOL_MAX_FIELDS)return FRACTAL_ERROR_INVALID_ARGUMENT;n=(uint8_t)(b[0]&0x1f);m->count=0;for(i=0;i<n;i++){if(!read_uint(b,len,&off,&k)||!read_uint(b,len,&off,&v)||k>UINT32_MAX)return FRACTAL_ERROR_INVALID_ARGUMENT;if(i>0&&m->fields[i-1].key>=k)return FRACTAL_ERROR_INVALID_ARGUMENT;if(reject_required&&k>=1000u)return FRACTAL_ERROR_INVALID_ARGUMENT;m->fields[i]=(fractal_cbor_pair){(uint32_t)k,v};m->count++;}if(off!=len)return FRACTAL_ERROR_INVALID_ARGUMENT;return FRACTAL_OK;}
uint64_t fractal_protocol_semantic_identity(const fractal_cbor_map*m){uint64_t h=UINT64_C(1469598103934665603);uint32_t i;if(!m)return 0;for(i=0;i<m->count;i++){h^=m->fields[i].key;h*=UINT64_C(1099511628211);h^=m->fields[i].value;h*=UINT64_C(1099511628211);}return h;}
