#ifndef FRACTAL_TRANSPORT_VALIDATION_H
#define FRACTAL_TRANSPORT_VALIDATION_H
#include <stdbool.h>
#include <stdint.h>
#include "fractal/workspace.h"
#include "fractal/intent_replay.h"
#include "fractal/reacquire.h"
#ifdef __cplusplus
extern "C" {
#endif
#define FRACTAL_VALIDATION_SCENARIO_CAPACITY 32u
#define FRACTAL_VALIDATION_INTENT_CAPACITY 12u
#define FRACTAL_VALIDATION_FAULT_CAPACITY 8u
typedef enum fractal_validation_transport{FRACTAL_VALIDATION_TRANSPORT_FAKE=0,FRACTAL_VALIDATION_TRANSPORT_UNIX_SOCKET,FRACTAL_VALIDATION_TRANSPORT_NAMED_PIPE,FRACTAL_VALIDATION_TRANSPORT_TLS13_LOOPBACK}fractal_validation_transport;
typedef enum fractal_validation_fault_kind{FRACTAL_FAULT_NONE=0,FRACTAL_FAULT_DROP_MESSAGE,FRACTAL_FAULT_DUPLICATE_MESSAGE,FRACTAL_FAULT_DELAY_MESSAGE,FRACTAL_FAULT_REORDER_MESSAGES,FRACTAL_FAULT_CORRUPT_FRAME,FRACTAL_FAULT_DROP_ACK,FRACTAL_FAULT_DISCONNECT,FRACTAL_FAULT_RECONNECT,FRACTAL_FAULT_NETWORK_CHANGE,FRACTAL_FAULT_CLIENT_SUSPEND,FRACTAL_FAULT_CLIENT_RESUME,FRACTAL_FAULT_SERVICE_RESTART,FRACTAL_FAULT_SERVICE_IDENTITY_ROTATION,FRACTAL_FAULT_CREDENTIAL_REVOCATION,FRACTAL_FAULT_CAPABILITY_CHANGE}fractal_validation_fault_kind;
typedef enum fractal_validation_fault_layer{FRACTAL_FAULT_LAYER_SEMANTIC_MESSAGE=0,FRACTAL_FAULT_LAYER_FRAME,FRACTAL_FAULT_LAYER_TRANSPORT_LIFECYCLE,FRACTAL_FAULT_LAYER_SERVICE_LIFECYCLE,FRACTAL_FAULT_LAYER_SECURITY_SESSION}fractal_validation_fault_layer;
typedef struct fractal_validation_fault{uint32_t scenario_step;uint64_t fault_identity;fractal_validation_fault_kind kind;fractal_validation_fault_layer layer;}fractal_validation_fault;
typedef struct fractal_validation_scenario{uint32_t contract_version;const char*scenario_id;fractal_workspace_id seed_owner;fractal_workspace_id seed_editor;fractal_workspace_id seed_observer;uint64_t creation_tick;uint64_t expected_transition_count;uint64_t expected_final_revision;uint64_t expected_final_generation;uint64_t expected_snapshot_identity;fractal_client_intent_kind actions[FRACTAL_VALIDATION_INTENT_CAPACITY];uint32_t action_count;fractal_validation_fault faults[FRACTAL_VALIDATION_FAULT_CAPACITY];uint32_t fault_count;}fractal_validation_scenario;
typedef struct fractal_validation_semantic_result{const char*scenario_id;fractal_workspace_id workspace_id;uint64_t final_revision;uint64_t final_generation;uint64_t final_snapshot_identity;uint64_t lease_epoch;fractal_workspace_capabilities participant_capabilities;fractal_intent_id accepted_intents[FRACTAL_VALIDATION_INTENT_CAPACITY];uint32_t accepted_count;fractal_intent_id rejected_intents[FRACTAL_VALIDATION_INTENT_CAPACITY];fractal_workspace_rejection rejected_reasons[FRACTAL_VALIDATION_INTENT_CAPACITY];uint32_t rejected_count;uint64_t replay_identities[FRACTAL_VALIDATION_INTENT_CAPACITY];uint32_t replay_count;uint64_t preview_identity;uint64_t analysis_identity;uint64_t artifact_identities[FRACTAL_WORKSPACE_ARTIFACT_CAPACITY];uint32_t artifact_count;uint64_t service_restart_epoch;fractal_reacquire_response_kind reacquisition_result;}fractal_validation_semantic_result;
typedef struct fractal_validation_drift_report{fractal_validation_transport expected_transport;fractal_validation_transport observed_transport;const char*scenario_id;uint32_t field_mismatches;uint64_t expected_identities;uint64_t observed_identities;uint32_t semantic_drift_count;}fractal_validation_drift_report;
uint64_t fractal_validation_snapshot_identity(const fractal_workspace_snapshot*snapshot);
uint32_t fractal_validation_scenario_count(void);
const fractal_validation_scenario*fractal_validation_scenario_at(uint32_t index);
int fractal_validation_run_scenario(const fractal_validation_scenario*scenario,fractal_validation_transport transport,fractal_validation_semantic_result*out);
fractal_validation_drift_report fractal_validation_compare(const fractal_validation_semantic_result*expected,fractal_validation_transport expected_transport,const fractal_validation_semantic_result*observed,fractal_validation_transport observed_transport);
#ifdef __cplusplus
}
#endif
#endif
