#ifndef FRACTAL_LOCAL_WORKSPACE_SERVICE_H
#define FRACTAL_LOCAL_WORKSPACE_SERVICE_H
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "fractal/workspace.h"
#include "fractal/intent_replay.h"
#include "fractal/reacquire.h"
#ifdef __cplusplus
extern "C" {
#endif
#define FRACTAL_LOCAL_SERVICE_CONTRACT_VERSION 1u
#define FRACTAL_LOCAL_SERVICE_MAX_SESSIONS 4u
#define FRACTAL_LOCAL_SERVICE_FRAME_LIMIT 4096u
#define FRACTAL_LOCAL_CHECKPOINT_MAGIC 0x5243465357435031ull
#define FRACTAL_LOCAL_SERVICE_ID_HIGH 0x4653575352560001ull
#define FRACTAL_LOCAL_SERVICE_ID_LOW 0x4c4f43414c000001ull
typedef enum fractal_workspace_lifetime_state{FRACTAL_WS_UNINITIALIZED=0,FRACTAL_WS_CREATED,FRACTAL_WS_OPEN,FRACTAL_WS_ACTIVE,FRACTAL_WS_IDLE,FRACTAL_WS_CHECKPOINTING,FRACTAL_WS_RESTORING,FRACTAL_WS_CLOSING,FRACTAL_WS_CLOSED,FRACTAL_WS_FAILED}fractal_workspace_lifetime_state;
typedef enum fractal_service_lifecycle{FRACTAL_SERVICE_STOPPED=0,FRACTAL_SERVICE_STARTING,FRACTAL_SERVICE_INITIALIZING,FRACTAL_SERVICE_READY,FRACTAL_SERVICE_DRAINING,FRACTAL_SERVICE_STOPPING,FRACTAL_SERVICE_FAILED}fractal_service_lifecycle;
typedef enum fractal_local_message_class{FRACTAL_MSG_COMPATIBILITY_HELLO=1,FRACTAL_MSG_COMPATIBILITY_RESULT,FRACTAL_MSG_LOCAL_SESSION_OPEN,FRACTAL_MSG_LOCAL_SESSION_RESULT,FRACTAL_MSG_WORKSPACE_OPEN,FRACTAL_MSG_WORKSPACE_SNAPSHOT_REQUEST,FRACTAL_MSG_WORKSPACE_SNAPSHOT,FRACTAL_MSG_CLIENT_INTENT,FRACTAL_MSG_WORKSPACE_TRANSITION,FRACTAL_MSG_REACQUIRE_REQUEST,FRACTAL_MSG_REACQUIRE_RESPONSE,FRACTAL_MSG_SERVICE_STATUS_REQUEST,FRACTAL_MSG_SERVICE_STATUS,FRACTAL_MSG_SESSION_CLOSE,FRACTAL_MSG_PROTOCOL_ERROR}fractal_local_message_class;
typedef struct fractal_workspace_lifetime_record{fractal_workspace_id workspace_id;fractal_workspace_lifetime_state state;uint64_t lifecycle_epoch;uint64_t state_revision;uint64_t generation;uint64_t service_restart_epoch;uint64_t checkpoint_revision;uint32_t restoration_result;uint32_t open_participant_count;bool active_controller;fractal_intent_id last_transition_identity;uint32_t bounded_error;}fractal_workspace_lifetime_record;
typedef struct fractal_local_peer_result{bool accepted;uint64_t normalized_peer_identity;uint32_t policy_code;}fractal_local_peer_result;
typedef struct fractal_local_service_status{fractal_service_lifecycle lifecycle;fractal_workspace_id service_id;uint64_t restart_epoch;uint32_t compatibility_selection;uint32_t workspace_count;fractal_workspace_lifetime_state workspace_lifecycle;uint64_t revision;uint64_t generation;uint32_t active_sessions;bool controller_lease_active;uint32_t last_checkpoint_result;bool runtime_available;uint32_t degraded_status;}fractal_local_service_status;
typedef struct fractal_local_service{fractal_service_lifecycle lifecycle;fractal_workspace_id service_id;uint64_t restart_epoch;fractal_workspace_state workspace;fractal_workspace_lifetime_record lifetime;fractal_replay_cache replay;uint32_t active_sessions;fractal_participant_id local_participant;fractal_local_service_status status;}fractal_local_service;
typedef struct fractal_local_transition_result{fractal_workspace_transition transition;fractal_replay_result_kind replay_kind;fractal_workspace_snapshot snapshot;}fractal_local_transition_result;
typedef struct fractal_local_checkpoint{uint64_t magic;uint32_t version;uint32_t size;fractal_workspace_state workspace;fractal_workspace_lifetime_record lifetime;fractal_replay_cache replay;uint64_t checksum;}fractal_local_checkpoint;
const char*fractal_workspace_lifetime_state_name(fractal_workspace_lifetime_state state);
const char*fractal_service_lifecycle_name(fractal_service_lifecycle state);
const char*fractal_local_message_class_name(fractal_local_message_class cls);
int fractal_workspace_lifetime_transition(fractal_workspace_lifetime_record*record,fractal_workspace_lifetime_state next,uint64_t restart_epoch);
void fractal_local_service_init(fractal_local_service*service,uint64_t restart_epoch);
fractal_local_peer_result fractal_local_operator_admit_current_user(void);
int fractal_local_service_open(fractal_local_service*service);
int fractal_local_service_open_session(fractal_local_service*service,fractal_local_peer_result peer,fractal_participant_id*out);
fractal_local_transition_result fractal_local_service_apply_intent(fractal_local_service*service,const fractal_client_intent*intent);
fractal_reacquire_response fractal_local_service_reacquire(fractal_local_service*service,const fractal_reacquire_request*request);
int fractal_local_service_snapshot(fractal_local_service*service,fractal_participant_id actor,fractal_workspace_snapshot*out);
fractal_local_service_status fractal_local_service_get_status(fractal_local_service*service);
int fractal_local_checkpoint_create(fractal_local_service*service,fractal_local_checkpoint*out);
int fractal_local_checkpoint_restore(fractal_local_service*service,const fractal_local_checkpoint*checkpoint,uint64_t restart_epoch);
int fractal_local_frame_encode(const uint8_t*payload,uint32_t payload_size,uint8_t*out,size_t out_capacity,size_t*written);
int fractal_local_frame_decode(const uint8_t*input,size_t input_size,uint8_t*out,size_t out_capacity,size_t*payload_size,size_t*consumed);
uint64_t fractal_local_semantic_digest(const fractal_local_service*service);
#ifdef __cplusplus
}
#endif
#endif
